/**
 * Configuración completa de módulos con lecciones y secciones
 * Ruta: Git → Java → SQL → Spring Boot
 */
import gitLogoImg from '../assets/images/logos/git-logo.png';
import githubLogoImg from '../assets/images/logos/github.jpeg';
import blancaJavaImg from '../assets/images/header/blancajava.jpeg';

export const modulesWithLessons = [
  {
    id: 'aws',
    name: 'Amazon Web Services',
    description: 'Servicios en la nube: EC2, RDS, S3, Lambda y despliegue profesional',
    landingPage: '/cloud/aws',
    sections: [
      {
        id: 'fundamentales',
        name: 'Fundamentales',
        description: 'Qué es AWS, conceptos clave, cuenta, IAM y pricing',
        lessons: [
          { title: 'Qué es AWS y por qué usarlo', link: '/cloud/aws/fundamentales/intro' },
          { title: 'Arquitectura de Software y Proveedores Cloud', link: '/cloud/aws/fundamentales/arquitectura' },
          { title: 'Conceptos Clave: Regiones, AZ, VPC', link: '/cloud/aws/fundamentales/conceptos' },
          { title: 'Gestión de Identidad y Acceso (IAM)', link: '/cloud/aws/fundamentales/iam' },
          { title: 'Pricing y Estimador de Costos', link: '/cloud/aws/fundamentales/pricing' },
        ]},
      {
        id: 'servicios',
        name: 'Servicios Principales',
        description: 'Servicios más usados: EC2, RDS, S3, Lambda, DynamoDB',
        lessons: [
          { title: 'EC2 - Máquinas Virtuales', link: '/cloud/aws/servicios/ec2' },
          { title: 'RDS - Bases de Datos Relacionales', link: '/cloud/aws/servicios/rds' },
          { title: 'S3 - Almacenamiento de Objetos', link: '/cloud/aws/servicios/s3' },
          { title: 'Lambda - Serverless Computing', link: '/cloud/aws/servicios/lambda' },
          { title: 'Comparación: EC2 vs Lambda', link: '/cloud/aws/comparacion-ec2-vs-lambda' },
          { title: 'DynamoDB - Base de Datos NoSQL', link: '/cloud/aws/servicios/dynamodb' },
          { title: 'Comparación: RDS vs DynamoDB', link: '/cloud/aws/comparacion-rds-vs-dynamodb' },
          { title: 'Almacenamiento (S3, EBS, EFS)', link: '/cloud/aws/servicios/almacenamiento' },
        ]},
      {
        id: 'redes',
        name: 'Redes & Seguridad',
        description: 'VPC, Security Groups, Route Tables, conectividad',
        lessons: [
          { title: 'VPC - Redes Privadas en AWS', link: '/cloud/aws/redes/vpc' },
          { title: 'Security Groups & Firewalls', link: '/cloud/aws/operaciones/seguridad' },
        ]},
      {
        id: 'deployment',
        name: 'Deployment & CI/CD',
        description: 'Desplegar aplicaciones: CloudFormation, CodePipeline, Blue/Green, Contenedores',
        lessons: [
          { title: 'Despliegue e Infraestructura como Código (IaC)', link: '/cloud/aws/deployment/cicd' },
          { title: 'Elastic Beanstalk - Deploy Simplificado', link: '/cloud/aws/deployment/beanstalk' },
          { title: 'ECS - Contenedores en AWS', link: '/cloud/aws/deployment/ecs' },
          { title: 'CloudFront - CDN Global', link: '/cloud/aws/deployment/cloudfront' },
        ]},
      {
        id: 'operaciones',
        name: 'Operaciones & Seguridad',
        description: 'CloudWatch, Security Groups, Backup y mejores prácticas',
        lessons: [
          { title: 'CloudWatch - Monitoreo y Logs', link: '/cloud/aws/operaciones/cloudwatch' },
          { title: 'Security Groups y VPC', link: '/cloud/aws/operaciones/seguridad' },
          { title: 'Backup y Recuperación', link: '/cloud/aws/operaciones/backup' },
          { title: 'Mejores Prácticas en AWS', link: '/cloud/aws/operaciones/practicas' },
        ]},
      {
        id: 'integracion',
        name: 'Integración & Lenguajes',
        description: 'Integración con Java, Spring Boot y SDKs',
        lessons: [
          { title: 'AWS SDK v2 con Java & Spring Boot', link: '/cloud/aws/integracion/java' },
        ]},
      {
        id: 'proyecto',
        name: 'TFC',
        description: 'Arquitectura completa integrada del Laboratorio Guttman',
        lessons: [
          { title: 'TFC: Arquitectura del Laboratorio Guttman', link: '/cloud/aws/proyecto/final' },
        ]},
    ],
    lessons: [
      { title: 'Qué es AWS y por qué usarlo', link: '/cloud/aws/fundamentales/intro' },
      { title: 'Arquitectura de Software y Proveedores Cloud', link: '/cloud/aws/fundamentales/arquitectura' },
      { title: 'Conceptos Clave: Regiones, AZ, VPC', link: '/cloud/aws/fundamentales/conceptos' },
      { title: 'Gestión de Identidad y Acceso (IAM)', link: '/cloud/aws/fundamentales/iam' },
      { title: 'Pricing y Estimador de Costos', link: '/cloud/aws/fundamentales/pricing' },
      { title: 'EC2 - Máquinas Virtuales', link: '/cloud/aws/servicios/ec2' },
      { title: 'RDS - Bases de Datos Relacionales', link: '/cloud/aws/servicios/rds' },
      { title: 'S3 - Almacenamiento de Objetos', link: '/cloud/aws/servicios/s3' },
      { title: 'Lambda - Serverless Computing', link: '/cloud/aws/servicios/lambda' },
      { title: 'Comparación: EC2 vs Lambda (Aclarando Confusiones)', link: '/cloud/aws/comparacion-ec2-vs-lambda' },
      { title: 'DynamoDB - Base de Datos NoSQL', link: '/cloud/aws/servicios/dynamodb' },
      { title: 'Comparación: RDS vs DynamoDB (SQL vs NoSQL)', link: '/cloud/aws/comparacion-rds-vs-dynamodb' },
      { title: 'Almacenamiento (S3, EBS, EFS)', link: '/cloud/aws/servicios/almacenamiento' },
      { title: 'VPC - Redes Privadas en AWS', link: '/cloud/aws/redes/vpc' },
      { title: 'Despliegue e Infraestructura como Código', link: '/cloud/aws/deployment/cicd' },
      { title: 'Elastic Beanstalk - Deploy Simplificado', link: '/cloud/aws/deployment/beanstalk' },
      { title: 'ECS - Contenedores en AWS', link: '/cloud/aws/deployment/ecs' },
      { title: 'CloudFront - CDN Global', link: '/cloud/aws/deployment/cloudfront' },
      { title: 'CloudWatch - Monitoreo y Logs', link: '/cloud/aws/operaciones/cloudwatch' },
      { title: 'Security Groups y Firewalls', link: '/cloud/aws/operaciones/seguridad' },
      { title: 'Backup y Recuperación', link: '/cloud/aws/operaciones/backup' },
      { title: 'Mejores Prácticas en AWS', link: '/cloud/aws/operaciones/practicas' },
      { title: 'AWS SDK v2 con Java & Spring Boot', link: '/cloud/aws/integracion/java' },
      { title: 'TFC: Arquitectura del Laboratorio Guttman', link: '/cloud/aws/proyecto/final' },
    ]},
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containerización, deployment y orquestación profesional',
    landingPage: '/cloud/docker',
    sections: [
      {
        id: 'fundamentales',
        name: 'Fundamentales',
        description: 'Aprende desde cero: qué es Docker, conceptos clave, tu primer contenedor y Dockerfile.',
        lessons: [
          { title: 'Qué es Docker y por qué lo necesitas', link: '/cloud/docker/fundamentales/intro' },
          { title: 'Conceptos: Imágenes, Contenedores, Volúmenes', link: '/cloud/docker/fundamentales/conceptos' },
          { title: 'Tu primer Dockerfile', link: '/cloud/docker/fundamentales/dockerfile' },
          { title: 'Comandos Esenciales de Docker', link: '/cloud/docker/fundamentales/comandos' },
          { title: 'Comparación: S3 vs Docker (Aclarando Confusiones)', link: '/cloud/docker/comparacion-s3-vs-docker' },
          { title: 'Comparación: Docker vs Kubernetes', link: '/cloud/docker/comparacion-docker-vs-kubernetes' },
        ]},
      {
        id: 'composicion',
        name: 'Multi-Contenedor',
        description: 'Docker Compose, networking, comunicación entre contenedores y volúmenes avanzados.',
        lessons: [
          { title: 'Docker Compose: Orquestación', link: '/cloud/docker/composicion/compose' },
          { title: 'Networking y DNS Interno', link: '/cloud/docker/composicion/networking' },
          { title: 'Volúmenes: Persistencia de Datos', link: '/cloud/docker/composicion/volumenes' },
        ]},
      {
        id: 'avanzado',
        name: 'Avanzado',
        description: 'Multi-stage builds, optimización, seguridad, debugging y mejores prácticas.',
        lessons: [
          { title: 'Multi-Stage Builds - Reducir Tamaño', link: '/cloud/docker/avanzado/multistage' },
          { title: 'Optimización y Seguridad', link: '/cloud/docker/avanzado/optimizacion' },
          { title: 'Debugging y Troubleshooting', link: '/cloud/docker/avanzado/debugging' },
          { title: 'Buenas Prácticas', link: '/cloud/docker/avanzado/practicas' },
        ]},
      {
        id: 'frameworks',
        name: 'Frameworks Populares',
        description: 'Dockerizar aplicaciones: Python/FastAPI, Java/Spring, Frontend/React, Node.js.',
        lessons: [
          { title: 'Backend: Python & FastAPI', link: '/cloud/docker/frameworks/python' },
          { title: 'Backend: Java & Spring Boot', link: '/cloud/docker/frameworks/java' },
          { title: 'Frontend: React, Angular, Vue', link: '/cloud/docker/frameworks/frontend' },
          { title: 'Node.js & Express', link: '/cloud/docker/frameworks/nodejs' },
        ]},
    ],
    lessons: [
      { title: 'Introducción: Qué es Docker y por qué lo necesitas', link: '/cloud/docker/fundamentales/intro' },
      { title: 'Conceptos: Imágenes, Contenedores, Volúmenes y Capas', link: '/cloud/docker/fundamentales/conceptos' },
      { title: 'Tu primer Dockerfile - Instrucciones principales', link: '/cloud/docker/fundamentales/dockerfile' },
      { title: 'Comandos Esenciales de Docker - Build, Run, Logs', link: '/cloud/docker/fundamentales/comandos' },
      { title: 'Comparación: S3 vs Docker (Aclarando Confusiones)', link: '/cloud/docker/comparacion-s3-vs-docker' },
      { title: 'Comparación: Docker vs Kubernetes (Contenedor vs Orquestador)', link: '/cloud/docker/comparacion-docker-vs-kubernetes' },
      { title: 'Docker Compose: Orquestación de Múltiples Contenedores', link: '/cloud/docker/composicion/compose' },
      { title: 'Networking y DNS Interno entre Contenedores', link: '/cloud/docker/composicion/networking' },
      { title: 'Volúmenes: Persistencia de Datos (Named vs Bind)', link: '/cloud/docker/composicion/volumenes' },
      { title: 'Multi-Stage Builds - Reducir Tamaño de Imágenes', link: '/cloud/docker/avanzado/multistage' },
      { title: 'Optimización: Alpine, Caché, Seguridad', link: '/cloud/docker/avanzado/optimizacion' },
      { title: 'Debugging y Troubleshooting - Logs, Exec, Stats', link: '/cloud/docker/avanzado/debugging' },
      { title: 'Buenas Prácticas Profesionales y Checklist', link: '/cloud/docker/avanzado/practicas' },
      { title: 'Backend: Python & FastAPI en Docker', link: '/cloud/docker/frameworks/python' },
      { title: 'Backend: Java & Spring Boot Multi-Stage', link: '/cloud/docker/frameworks/java' },
      { title: 'Frontend: React, Angular, Vue - Multi-Stage', link: '/cloud/docker/frameworks/frontend' },
      { title: 'Node.js & Express - Alpine y Producción', link: '/cloud/docker/frameworks/nodejs' },
    ]},
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description: 'Orquestación de contenedores a escala empresarial',
    landingPage: '/cloud/kubernetes',
    sections: [
      {
        id: 'fundamentales',
        name: 'Fundamentales',
        description: 'Aprende desde cero: qué es K8s, arquitectura, Pods, Deployments, Services.',
        lessons: [
          { title: 'Introducción: Qué es Kubernetes', link: '/cloud/kubernetes/fundamentales/intro' },
          { title: 'Pods: La unidad más pequeña', link: '/cloud/kubernetes/fundamentales/pods' },
          { title: 'Deployments: Gestión de réplicas', link: '/cloud/kubernetes/fundamentales/deployments' },
        ]},
    ],
    lessons: [
      { title: 'Introducción: Qué es Kubernetes', link: '/cloud/kubernetes/fundamentales/intro' },
      { title: 'Pods: La unidad más pequeña', link: '/cloud/kubernetes/fundamentales/pods' },
      { title: 'Deployments: Gestión de réplicas', link: '/cloud/kubernetes/fundamentales/deployments' },
      { title: 'Comparación: Docker vs Kubernetes (Aclarando Confusiones)', link: '/cloud/docker/comparacion-docker-vs-kubernetes' },
    ]},
  {
    id: 'git',
    name: 'Git',
    icon: gitLogoImg,
    description: 'Control de versiones y colaboración',
    landingPage: '/control-versiones/git',
    sections: [
      {
        id: 'basicos',
        name: 'Git Básicos',
        description: 'Domina los fundamentos: configuración, repositorios, commits, ramas y merge. Todo lo que necesitas para comenzar con Git.',
        lessons: [
          { title: 'Configuración inicial de Git', link: '/control-versiones/git/basicos/configuracion-inicial' },
          { title: 'Crear y clonar repositorios', link: '/control-versiones/git/basicos/crear-clonar-repos' },
          { title: 'Commits y mensajes claros', link: '/control-versiones/git/basicos/commits' },
          { title: 'Ramas (branches)', link: '/control-versiones/git/basicos/branches' },
          { title: 'Merge y resolución de conflictos', link: '/control-versiones/git/basicos/merge' },
          { title: 'Configuración de Alias en Git', link: '/control-versiones/git/basicos/alias' },
          { title: 'Errores Comunes en Git', link: '/control-versiones/git/basicos/errores-comunes' },
        ]},
      {
        id: 'avanzado',
        name: 'Remoto y Colaboración',
        description: 'Sincronización remota, pull requests y plataformas colaborativas. Aprende a trabajar en equipo y gestionar proyectos profesionales.',
        lessons: [
          { title: 'Push, Pull y Fetch', link: '/control-versiones/git/avanzado/push-pull-fetch' },
          { title: 'Pull requests y colaboración', link: '/control-versiones/git/avanzado/pull-requests' },
          { title: 'GitHub, GitLab y Bitbucket', link: '/control-versiones/git/avanzado/plataformas-remotas' },
          { title: 'Git Workflow y Conventional Commits', link: '/control-versiones/git/avanzado/workflow' },
          { title: 'GitHub', link: '/control-versiones/git/avanzado/github' },
          { title: 'GitLab', link: '/control-versiones/git/avanzado/gitlab' },
          { title: 'Bitbucket', link: '/control-versiones/git/avanzado/bitbucket' },
        ]},
      {
        id: 'practicas',
        name: 'Prácticas con Git',
        description: 'Ejercicios prácticos para poner en práctica lo aprendido. Realiza tareas reales de configuración y uso de Git.',
        lessons: [
          { title: 'Práctica: Configura tu Git', link: '/control-versiones/git/practicas/configura-tu-git' },
          { title: 'Práctica: Crea tu Primer Repositorio', link: '/control-versiones/git/practicas/crea-tu-primer-repositorio' },
          { title: 'Práctica: Haz tus Primeros Commits', link: '/control-versiones/git/practicas/haz-tus-primeros-commits' },
          { title: 'Práctica: Trabaja con Ramas', link: '/control-versiones/git/practicas/trabaja-con-ramas' },
          { title: 'Práctica: Resuelve Conflictos de Merge', link: '/control-versiones/git/practicas/resuelve-conflictos-de-merge' },
        ]},
    ],
    lessons: [
      { title: 'Configuración inicial de Git', link: '/control-versiones/git/basicos/configuracion-inicial' },
      { title: 'Crear y clonar repositorios', link: '/control-versiones/git/basicos/crear-clonar-repos' },
      { title: 'Commits y mensajes claros', link: '/control-versiones/git/basicos/commits' },
      { title: 'Ramas (branches)', link: '/control-versiones/git/basicos/branches' },
      { title: 'Merge y resolución de conflictos', link: '/control-versiones/git/basicos/merge' },
      { title: 'Configuración de Alias en Git', link: '/control-versiones/git/basicos/alias' },
      { title: 'Errores Comunes en Git', link: '/control-versiones/git/basicos/errores-comunes' },
      { title: 'Push, Pull y Fetch', link: '/control-versiones/git/avanzado/push-pull-fetch' },
      { title: 'Pull requests y colaboración', link: '/control-versiones/git/avanzado/pull-requests' },
      { title: 'GitHub, GitLab y Bitbucket', link: '/control-versiones/git/avanzado/plataformas-remotas' },
      { title: 'Git Workflow y Conventional Commits', link: '/control-versiones/git/avanzado/workflow' },
      { title: 'GitHub', link: '/control-versiones/git/avanzado/github' },
      { title: 'GitLab', link: '/control-versiones/git/avanzado/gitlab' },
      { title: 'Bitbucket', link: '/control-versiones/git/avanzado/bitbucket' },
    ]},
  {
    id: 'github',
    name: 'GitHub',
    icon: githubLogoImg,
    description: 'Plataforma colaborativa: repositorios, flujos de trabajo y colaboración en equipo',
    landingPage: '/control-versiones/github',
    sections: [
      {
        id: 'basicos',
        name: 'GitHub Básicos',
        description: 'Configuración inicial, repositorios y primeros pasos con GitHub',
        lessons: [
          { title: 'Qué es GitHub y por qué usarlo', link: '/control-versiones/github/basicos/intro' },
          { title: 'Crear una cuenta y configurar perfil', link: '/control-versiones/github/basicos/crear-cuenta' },
          { title: 'Crear y clonar repositorios en GitHub', link: '/control-versiones/github/basicos/crear-clonar-repos' },
          { title: 'Push, Pull y sincronización', link: '/control-versiones/github/basicos/push-pull' },
        ]},
      {
        id: 'colaboracion',
        name: 'Colaboración y Flujos de Trabajo',
        description: 'Pull requests, issues, forks y trabajo en equipo profesional',
        lessons: [
          { title: 'Pull Requests: crear y gestionar', link: '/control-versiones/github/colaboracion/pull-requests' },
          { title: 'Forks y contribuciones', link: '/control-versiones/github/colaboracion/forks' },
          { title: 'Issues y Project Boards', link: '/control-versiones/github/colaboracion/issues' },
          { title: 'GitHub Flow: flujo de trabajo profesional', link: '/control-versiones/github/colaboracion/github-flow' },
        ]},
      {
        id: 'avanzado',
        name: 'Funcionalidades Avanzadas',
        description: 'Actions, workflows, seguridad y automatización',
        lessons: [
          { title: 'GitHub Actions: automatización y CI/CD', link: '/control-versiones/github/avanzado/actions' },
          { title: 'Protección de ramas y políticas', link: '/control-versiones/github/avanzado/branch-protection' },
          { title: 'Seguridad y tokens personales', link: '/control-versiones/github/avanzado/seguridad' },
        ]},
    ],
    lessons: [
      { title: 'Qué es GitHub y por qué usarlo', link: '/control-versiones/github/basicos/intro' },
      { title: 'Crear una cuenta y configurar perfil', link: '/control-versiones/github/basicos/crear-cuenta' },
      { title: 'Crear y clonar repositorios en GitHub', link: '/control-versiones/github/basicos/crear-clonar-repos' },
      { title: 'Push, Pull y sincronización', link: '/control-versiones/github/basicos/push-pull' },
      { title: 'Pull Requests: crear y gestionar', link: '/control-versiones/github/colaboracion/pull-requests' },
      { title: 'Forks y contribuciones', link: '/control-versiones/github/colaboracion/forks' },
      { title: 'Issues y Project Boards', link: '/control-versiones/github/colaboracion/issues' },
      { title: 'GitHub Flow: flujo de trabajo profesional', link: '/control-versiones/github/colaboracion/github-flow' },
      { title: 'GitHub Actions: automatización y CI/CD', link: '/control-versiones/github/avanzado/actions' },
      { title: 'Protección de ramas y políticas', link: '/control-versiones/github/avanzado/branch-protection' },
      { title: 'Seguridad y tokens personales', link: '/control-versiones/github/avanzado/seguridad' },
    ]},
  {
    id: 'java',
    name: 'Java',
    description: 'Domina Java: desde fundamentos hasta patrones avanzados y persistencia de datos',
    landingPage: '/backend/java',
    sections: [
      {
        id: 'introduccion',
        name: 'Java I: Introducción',
        fullName: 'Java I: Introducción',
        description: 'Fundamentos esenciales: tipos de datos, control de flujo, strings, arrays y excepciones.',
        lessons: [
          { title: 'Tipos de Datos', description: 'Primitivos e Wrappers: int, double, boolean, String y conversiones', link: '/backend/java/introduccion/tipos-datos' },
          { title: 'Control de Flujo', description: 'If/else, switch, bucles (for, while) y flujo de ejecución', link: '/backend/java/introduccion/control-flujo' },
          { title: 'Strings y Texto', description: 'Manipulación de cadenas, métodos útiles y StringBuilder', link: '/backend/java/introduccion/strings' },
          { title: 'Arrays y Matrices', description: 'Arreglos unidimensionales y bidimensionales, iteración', link: '/backend/java/introduccion/arrays' },
          { title: 'Scanner e Entrada', description: 'Lectura de entrada del usuario desde consola', link: '/backend/java/introduccion/scanner' },
          { title: 'Excepciones', description: 'Try/catch/finally, tipos de excepciones y manejo de errores', link: '/backend/java/introduccion/excepciones' },
          { title: 'Operadores', description: 'Operadores aritméticos, lógicos, comparación y asignación', link: '/backend/java/introduccion/operadores' },
        ]},
      {
        id: 'oop',
        name: 'Java II: Orientación a Objetos',
        fullName: 'Java II: Orientación a Objetos',
        description: 'Domina los pilares de la POO: clases, herencia, polimorfismo e interfaces.',
        lessons: [
          { title: 'Clases y Objetos', description: 'Definición, atributos, métodos, constructores y encapsulación', link: '/backend/java/oop/clases-objetos' },
          { title: 'Herencia', description: 'Extensión de clases, super(), método toString() y reuso de código', link: '/backend/java/oop/herencia' },
          { title: 'Polimorfismo', description: 'Sobreescritura de métodos, ligadura dinámica y flexibilidad de código', link: '/backend/java/oop/polimorfismo' },
          { title: 'Interfaces y Clases Abstractas', description: 'Contratos, abstracción y múltiple herencia con interfaces', link: '/backend/java/oop/interfaces-abstractas' },
        ]},
      {
        id: 'avanzado',
        name: 'Java III: Avanzado',
        fullName: 'Java III: Avanzado',
        description: 'Conceptos avanzados: colecciones, lambdas, streams, genéricos y la JVM.',
        lessons: [
          { title: 'Fundamentos de la Máquina de Java', description: 'Cómo funciona la JVM, bytecode, garbage collection y optimización', link: '/backend/java/avanzado/jvm' },
          { title: 'Colecciones en Java', description: 'List, Set, Map, iteradores y frameworks de colecciones', link: '/backend/java/avanzado/colecciones' },
          { title: 'Expresiones Lambda', description: 'Sintaxis lambda, interfaces funcionales y referencias a métodos', link: '/backend/java/avanzado/lambdas' },
          { title: 'Streams API', description: 'Procesamiento funcional de datos, map, filter, reduce', link: '/backend/java/avanzado/streams' },
          { title: 'Genéricos', description: 'Type parameters, wildcards, erasura y type safety', link: '/backend/java/avanzado/genericos' },
        ]},
      {
        id: 'persistencia',
        name: 'Java + BBDD',
        fullName: 'Java + Bases de Datos',
        description: 'JDBC, CRUD y persistencia: gestiona datos en bases de datos.',
        lessons: [
          { title: 'JDBC - Conectar a Bases de Datos', description: 'DriverManager, Connection, Statement, ResultSet y operaciones SQL', link: '/backend/java/persistencia/jdbc' },
          { title: 'CRUD y Transacciones', description: 'Operaciones Create, Read, Update, Delete y gestión de transacciones', link: '/backend/java/persistencia/crud' },
        ]},
    ],
    lessons: [
      { title: 'Tipos de Datos', link: '/backend/java/introduccion/tipos-datos' },
      { title: 'Control de Flujo', link: '/backend/java/introduccion/control-flujo' },
      { title: 'Strings y Texto', link: '/backend/java/introduccion/strings' },
      { title: 'Arrays y Matrices', link: '/backend/java/introduccion/arrays' },
      { title: 'Scanner e Entrada', link: '/backend/java/introduccion/scanner' },
      { title: 'Excepciones', link: '/backend/java/introduccion/excepciones' },
      { title: 'Operadores', link: '/backend/java/introduccion/operadores' },
      { title: 'Clases y Objetos', link: '/backend/java/oop/clases-objetos' },
      { title: 'Herencia', link: '/backend/java/oop/herencia' },
      { title: 'Polimorfismo', link: '/backend/java/oop/polimorfismo' },
      { title: 'Interfaces y Clases Abstractas', link: '/backend/java/oop/interfaces-abstractas' },
      { title: 'Fundamentos de la Máquina de Java', link: '/backend/java/avanzado/jvm' },
      { title: 'Colecciones en Java', link: '/backend/java/avanzado/colecciones' },
      { title: 'Expresiones Lambda', link: '/backend/java/avanzado/lambdas' },
      { title: 'Streams API', link: '/backend/java/avanzado/streams' },
      { title: 'Genéricos', link: '/backend/java/avanzado/genericos' },
      { title: 'JDBC - Conectar a Bases de Datos', link: '/backend/java/persistencia/jdbc' },
      { title: 'CRUD y Transacciones', link: '/backend/java/persistencia/crud' },
    ]},
  {
    id: 'kotlin',
    name: 'Kotlin',
    description: 'Lenguaje moderno para la JVM, más conciso que Java',
    landingPage: '/backend/kotlin',
    sections: [
      {
        id: 'introduccion',
        name: 'Introducción',
        description: 'Fundamentos de Kotlin y ventajas sobre Java',
        lessons: [
          { title: 'Introducción a Kotlin', link: '/backend/kotlin/introduccion' },
          { title: 'Kotlin vs Java', link: '/backend/kotlin/kotlin-vs-java' },
          { title: 'Sintaxis básica', link: '/backend/kotlin/sintaxis' },
        ]},
      {
        id: 'caracteristicas',
        name: 'Características',
        description: 'Null safety, extensiones, lambdas y corrutinas',
        lessons: [
          { title: 'Null Safety', link: '/backend/kotlin/null-safety' },
          { title: 'Funciones de Extensión', link: '/backend/kotlin/extension-functions' },
          { title: 'Lambdas y Funciones Literales', link: '/backend/kotlin/lambdas' },
          { title: 'Corrutinas', link: '/backend/kotlin/corrutinas' },
        ]},
      {
        id: 'avanzado',
        name: 'Avanzado',
        description: 'POO en Kotlin, DSLs y patrones avanzados',
        lessons: [
          { title: 'Clases y Objetos', link: '/backend/kotlin/clases-objetos' },
          { title: 'Scope Functions', link: '/backend/kotlin/scope-functions' },
          { title: 'DSLs en Kotlin', link: '/backend/kotlin/dsls' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Kotlin', link: '/backend/kotlin/introduccion' },
      { title: 'Kotlin vs Java', link: '/backend/kotlin/kotlin-vs-java' },
      { title: 'Sintaxis básica', link: '/backend/kotlin/sintaxis' },
      { title: 'Null Safety', link: '/backend/kotlin/null-safety' },
      { title: 'Funciones de Extensión', link: '/backend/kotlin/extension-functions' },
      { title: 'Lambdas y Funciones Literales', link: '/backend/kotlin/lambdas' },
      { title: 'Corrutinas', link: '/backend/kotlin/corrutinas' },
      { title: 'Clases y Objetos', link: '/backend/kotlin/clases-objetos' },
      { title: 'Scope Functions', link: '/backend/kotlin/scope-functions' },
      { title: 'DSLs en Kotlin', link: '/backend/kotlin/dsls' },
    ]},
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript en el servidor, APIs REST, y aplicaciones backend',
    landingPage: '/backend/nodejs',
    sections: [
      {
        id: 'introduccion',
        name: 'Introducción',
        description: 'Fundamentos de Node.js y el servidor JavaScript',
        lessons: [
          { title: 'Introducción a Node.js', link: '/backend/nodejs/introduccion' },
          { title: 'NPM y gestión de paquetes', link: '/backend/nodejs/npm' },
          { title: 'Módulos y require/import', link: '/backend/nodejs/modulos' },
          { title: 'Event Loop y asincronía', link: '/backend/nodejs/event-loop' },
        ]},
      {
        id: 'servidores',
        name: 'Servidores',
        description: 'HTTP, Express y construcción de APIs',
        lessons: [
          { title: 'HTTP y servidores nativos', link: '/backend/nodejs/http' },
          { title: 'Express.js - Framework web', link: '/backend/nodejs/express' },
          { title: 'Routing y middleware', link: '/backend/nodejs/routing' },
          { title: 'APIs REST', link: '/backend/nodejs/rest-apis' },
        ]},
      {
        id: 'datos',
        name: 'Datos',
        description: 'Bases de datos, conexiones y persistencia',
        lessons: [
          { title: 'Conexión a bases de datos', link: '/backend/nodejs/bases-datos' },
          { title: 'Sequelize y ORMs', link: '/backend/nodejs/sequelize' },
          { title: 'Gestión de transacciones', link: '/backend/nodejs/transacciones' },
        ]},
      {
        id: 'avanzado',
        name: 'Avanzado',
        description: 'Testing, autenticación y mejores prácticas',
        lessons: [
          { title: 'Autenticación y JWT', link: '/backend/nodejs/jwt' },
          { title: 'Testing en Node.js', link: '/backend/nodejs/testing' },
          { title: 'Despliegue y producción', link: '/backend/nodejs/despliegue' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Node.js', link: '/backend/nodejs/introduccion' },
      { title: 'NPM y gestión de paquetes', link: '/backend/nodejs/npm' },
      { title: 'Módulos y require/import', link: '/backend/nodejs/modulos' },
      { title: 'Event Loop y asincronía', link: '/backend/nodejs/event-loop' },
      { title: 'HTTP y servidores nativos', link: '/backend/nodejs/http' },
      { title: 'Express.js - Framework web', link: '/backend/nodejs/express' },
      { title: 'Routing y middleware', link: '/backend/nodejs/routing' },
      { title: 'APIs REST', link: '/backend/nodejs/rest-apis' },
      { title: 'Conexión a bases de datos', link: '/backend/nodejs/bases-datos' },
      { title: 'Sequelize y ORMs', link: '/backend/nodejs/sequelize' },
      { title: 'Gestión de transacciones', link: '/backend/nodejs/transacciones' },
      { title: 'Autenticación y JWT', link: '/backend/nodejs/jwt' },
      { title: 'Testing en Node.js', link: '/backend/nodejs/testing' },
      { title: 'Despliegue y producción', link: '/backend/nodejs/despliegue' },
    ]},
  {
    id: 'sql',
    name: 'SQL - Bases de Datos',
    description: 'DDL, DML, JOINs, consultas complejas',
    landingPage: '/datos/sql',
    sections: [
      {
        id: 'basicos',
        name: 'Fundamentos SQL',
        description: 'Introducción, DDL, DML y primeros pasos',
        lessons: [
          { title: 'Introducción a SQL y Bases de Datos', link: '/datos/sql/introduccion' },
          { title: 'DDL - Data Definition Language', link: '/datos/sql/ddl' },
          { title: 'DML - Data Manipulation Language', link: '/datos/sql/dml' },
        ]},
      {
        id: 'avanzado',
        name: 'Consultas Avanzadas',
        description: 'JOINs, subconsultas y optimización',
        lessons: [
          { title: 'JOINs - Combinando Tablas', link: '/datos/sql/joins' },
          { title: 'Consultas Avanzadas', link: '/datos/sql/consultas-avanzadas' },
        ]},
      {
        id: 'gestion',
        name: 'Gestión de BBDD',
        description: 'Administración: crear BD, usuarios, perfiles y permisos',
        lessons: [
          { title: 'Crear y Administrar Bases de Datos', link: '/datos/sql/gestion/crear-bases-datos' },
          { title: 'Usuarios y Permisos', link: '/datos/sql/gestion/usuarios-permisos' },
          { title: 'Backup y Recuperación', link: '/datos/sql/gestion/backup-recuperacion' },
        ]},
      {
        id: 'lenguajes',
        name: 'Lenguajes de BBDD',
        description: 'SQL vs NoSQL: MySQL, PostgreSQL, MongoDB, etc.',
        lessons: [
          { title: 'SQL vs NoSQL - Comparativa', link: '/datos/sql/lenguajes/sql-nosql' },
          { title: 'MySQL - SQL Relacional', link: '/datos/sql/lenguajes/mysql' },
          { title: 'PostgreSQL - SQL Avanzado', link: '/datos/sql/lenguajes/postgresql' },
          { title: 'MongoDB - NoSQL Flexible', link: '/datos/sql/lenguajes/mongodb' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a SQL y Bases de Datos', link: '/datos/sql/introduccion' },
      { title: 'DDL - Data Definition Language', link: '/datos/sql/ddl' },
      { title: 'DML - Data Manipulation Language', link: '/datos/sql/dml' },
      { title: 'JOINs - Combinando Tablas', link: '/datos/sql/joins' },
      { title: 'Consultas Avanzadas', link: '/datos/sql/consultas-avanzadas' },
      { title: 'Crear y Administrar Bases de Datos', link: '/datos/sql/gestion/crear-bases-datos' },
      { title: 'Usuarios y Permisos', link: '/datos/sql/gestion/usuarios-permisos' },
      { title: 'Backup y Recuperación', link: '/datos/sql/gestion/backup-recuperacion' },
      { title: 'SQL vs NoSQL - Comparativa', link: '/datos/sql/lenguajes/sql-nosql' },
      { title: 'MySQL - SQL Relacional', link: '/datos/sql/lenguajes/mysql' },
      { title: 'PostgreSQL - SQL Avanzado', link: '/datos/sql/lenguajes/postgresql' },
      { title: 'MongoDB - NoSQL Flexible', link: '/datos/sql/lenguajes/mongodb' },
    ]},
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    description: 'Aplicaciones web profesionales con Spring Boot',
    landingPage: '/backend/spring-boot',
    sections: [
      {
        id: 'fundamentos',
        name: 'Spring Boot Fundamentos',
        description: 'Introducción, setup, configuración inicial',
        lessons: [
          { title: 'Introducción a Spring Boot', link: '/backend/spring-boot/fundamentos/introduccion' },
          { title: 'Setup y Configuración', link: '/backend/spring-boot/fundamentos/configuracion' },
          { title: 'Controladores y Rutas', link: '/backend/spring-boot/fundamentos/controladores' },
        ]},
      {
        id: 'avanzado',
        name: 'Spring Boot Avanzado',
        description: 'Servicios, JPA, validación, testing, seguridad',
        lessons: [
          { title: 'Servicios y Lógica de Negocio', link: '/backend/spring-boot/avanzado/servicios' },
          { title: 'Acceso a Datos con JPA', link: '/backend/spring-boot/avanzado/jpa-hibernate' },
          { title: 'Validación y Manejo de Errores', link: '/backend/spring-boot/avanzado/validacion' },
          { title: 'Testing', link: '/backend/spring-boot/avanzado/testing' },
          { title: 'Seguridad con Spring Security', link: '/backend/spring-boot/avanzado/spring-security' },
          { title: 'OAuth2 & JWT - Autenticación Profesional', link: '/backend/spring-boot/avanzado/oauth2-jwt' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Spring Boot', link: '/backend/spring-boot/fundamentos/introduccion' },
      { title: 'Setup y Configuración', link: '/backend/spring-boot/fundamentos/configuracion' },
      { title: 'Controladores y Rutas', link: '/backend/spring-boot/fundamentos/controladores' },
      { title: 'Servicios y Lógica de Negocio', link: '/backend/spring-boot/avanzado/servicios' },
      { title: 'Acceso a Datos con JPA', link: '/backend/spring-boot/avanzado/jpa-hibernate' },
      { title: 'Validación y Manejo de Errores', link: '/backend/spring-boot/avanzado/validacion' },
      { title: 'Testing', link: '/backend/spring-boot/avanzado/testing' },
      { title: 'Seguridad con Spring Security', link: '/backend/spring-boot/avanzado/spring-security' },
      { title: 'OAuth2 & JWT - Autenticación Profesional', link: '/backend/spring-boot/avanzado/oauth2-jwt' },
    ]},
  {
    id: 'entornos',
    name: 'Entornos de Desarrollo',
    description: 'Herramientas, IDEs, arquitectura y mejores prácticas profesionales',
    sections: [
      {
        id: 'herramientas',
        name: 'Herramientas',
        description: 'IDEs, editores y herramientas esenciales de desarrollo',
        landingPage: '/herramientas/entornos/herramientas',
        lessons: [
          { title: 'Concepto de Entorno de Desarrollo', link: '/herramientas/entornos/herramientas/concepto' },
          { title: 'IDEs y Editores', link: '/herramientas/entornos/herramientas/ides' },
          { title: 'Codeium AI', link: '/herramientas/entornos/herramientas/codeium' },
        ]},
      {
        id: 'arquitectura',
        name: 'Arquitectura y Patrones',
        description: 'Arquitectura de software, patrones y mejores prácticas',
        landingPage: '/herramientas/entornos/arquitectura',
        lessons: [
          { title: 'UML y Diagramas', link: '/herramientas/entornos/arquitectura/uml' },
          { title: 'Patrones de Diseño', link: '/herramientas/entornos/arquitectura/patrones' },
          { title: 'Conceptos de Desarrollo', link: '/herramientas/entornos/arquitectura/conceptos' },
          { title: 'Testing y QA', link: '/herramientas/entornos/arquitectura/testing' },
          { title: 'Refactorización y SOLID', link: '/herramientas/entornos/arquitectura/refactoring' },
        ]},
      {
        id: 'build-tools',
        name: 'Build & Herramientas',
        description: 'Maven, Gradle y construcción de proyectos profesionales',
        landingPage: '/herramientas/entornos/build',
        lessons: [
          { title: 'Maven - Gestión de Proyectos', link: '/herramientas/entornos/build/maven' },
          { title: 'Gradle - Build Avanzado', link: '/herramientas/entornos/build/gradle' },
          { title: 'Gestión de Dependencias', link: '/herramientas/entornos/build/dependencias' },
        ]},
      {
        id: 'devops',
        name: 'DevOps & Deployment',
        description: 'Docker, CI/CD, containerización y despliegue profesional',
        lessons: [
          { title: 'Docker - Containerización', link: '/herramientas/entornos/devops/docker' },
          { title: 'Docker Compose - Multi-contenedor', link: '/herramientas/entornos/devops/docker-compose' },
          { title: 'CI/CD - Automatización', link: '/herramientas/entornos/devops/cicd' },
          { title: 'GitHub Actions', link: '/herramientas/entornos/devops/github-actions' },
          { title: 'Despliegue en Cloud', link: '/herramientas/entornos/devops/cloud-deployment' },
        ]},
    ],
    lessons: [
      { title: 'Concepto de Entorno de Desarrollo', link: '/herramientas/entornos/herramientas/concepto' },
      { title: 'IDEs y Editores', link: '/herramientas/entornos/herramientas/ides' },
      { title: 'Codeium AI', link: '/herramientas/entornos/herramientas/codeium' },
      { title: 'UML y Diagramas', link: '/herramientas/entornos/arquitectura/uml' },
      { title: 'Patrones de Diseño', link: '/herramientas/entornos/arquitectura/patrones' },
      { title: 'Conceptos de Desarrollo', link: '/herramientas/entornos/arquitectura/conceptos' },
      { title: 'Testing y QA', link: '/herramientas/entornos/arquitectura/testing' },
      { title: 'Refactorización y SOLID', link: '/herramientas/entornos/arquitectura/refactoring' },
      { title: 'Maven - Gestión de Proyectos', link: '/herramientas/entornos/build/maven' },
      { title: 'Gradle - Build Avanzado', link: '/herramientas/entornos/build/gradle' },
      { title: 'Gestión de Dependencias', link: '/herramientas/entornos/build/dependencias' },
      { title: 'Docker - Containerización', link: '/herramientas/entornos/devops/docker' },
      { title: 'Docker Compose - Multi-contenedor', link: '/herramientas/entornos/devops/docker-compose' },
      { title: 'CI/CD - Automatización', link: '/herramientas/entornos/devops/cicd' },
      { title: 'GitHub Actions', link: '/herramientas/entornos/devops/github-actions' },
      { title: 'Despliegue en Cloud (Vercel, Heroku, AWS, Azure)', link: '/herramientas/entornos/devops/cloud-deployment' },
    ]},
  {
    id: 'proyecto',
    name: 'TFC',
    description: 'Trabajo Fin de Ciclo integrando Java Backend, Spring Boot, Bases de Datos y más',
    landingPage: '/proyecto',
    sections: [
      {
        id: 'planificacion',
        name: 'Planificación',
        description: 'Definición de requisitos, arquitectura y diseño del proyecto',
        lessons: [
          { title: 'Definición del Proyecto', link: '/proyecto/planificacion/definicion' },
          { title: 'Requisitos y Especificaciones', link: '/proyecto/planificacion/requisitos' },
          { title: 'Arquitectura y Diseño', link: '/proyecto/planificacion/arquitectura' },
          { title: 'Ejemplos de Proyectos TFC', link: '/proyecto/planificacion/ejemplos' },
        ]},
      {
        id: 'metodologia',
        name: 'Metodología',
        description: 'Agile, SCRUM y gestión del proyecto con Taiga',
        lessons: [
          { title: 'Agile y SCRUM', link: '/proyecto/metodologia/agile-scrum' },
          { title: 'Sprint 1', link: '/proyecto/metodologia/sprint-1' },
          { title: 'Sprint 2', link: '/proyecto/metodologia/sprint-2' },
        ]},
      {
        id: 'desarrollo',
        name: 'Desarrollo',
        description: 'Implementación del backend con Java y Spring Boot',
        lessons: [
          { title: 'Setup del Proyecto', link: '/proyecto/desarrollo/setup' },
          { title: 'Desarrollo Backend', link: '/proyecto/desarrollo/backend' },
          { title: 'Base de Datos', link: '/proyecto/desarrollo/database' },
          { title: 'APIs REST', link: '/proyecto/desarrollo/apis' },
        ]},
      {
        id: 'testing',
        name: 'Testing',
        description: 'Pruebas unitarias, integración y validación',
        lessons: [
          { title: 'Testing Unitario', link: '/proyecto/testing/unitario' },
          { title: 'Testing de Integración', link: '/proyecto/testing/integracion' },
          { title: 'Validación Final', link: '/proyecto/testing/validacion' },
        ]},
      {
        id: 'despliegue',
        name: 'Despliegue',
        description: 'Empaquetado, documentación y despliegue a producción',
        lessons: [
          { title: 'Empaquetado y Build', link: '/proyecto/despliegue/build' },
          { title: 'Documentación', link: '/proyecto/despliegue/documentacion' },
          { title: 'Despliegue en Cloud', link: '/proyecto/despliegue/cloud' },
        ]},
      {
        id: 'retos',
        name: 'Retos DAW',
        description: 'Los 8 Retos del currículo con especificaciones y soluciones',
        lessons: [
          { title: 'REPTE 1: Especificación', link: '/proyecto/retos/1' },
          { title: 'REPTE 2: Especificación Técnica', link: '/proyecto/retos/2' },
          { title: 'REPTE 3: Elevator Pitch', link: '/proyecto/retos/3' },
          { title: 'REPTE 4: Organización Equipo', link: '/proyecto/retos/4' },
          { title: 'REPTE 5: Agile & SCRUM', link: '/proyecto/retos/5' },
          { title: 'REPTE 6: Sprint 1', link: '/proyecto/retos/6' },
          { title: 'REPTE 7: Sprint 2', link: '/proyecto/retos/7' },
          { title: 'REPTE 8: Sprint Final', link: '/proyecto/retos/8' },
        ]},
      {
        id: 'ejemplos',
        name: 'Ejemplos de TFC',
        description: '12+ proyectos desarrollados y viables para tu Trabajo de Fin de Curso',
        lessons: [
          { title: 'LibroHub - Marketplace de Libros Usados', link: '/proyecto/ejemplos/1' },
          { title: 'SportGear - E-commerce de Equipamiento', link: '/proyecto/ejemplos/2' },
          { title: 'ClinicaPro - Gestión de Clínica Médica', link: '/proyecto/ejemplos/3' },
          { title: 'PropertyHub - Plataforma de Alquiler', link: '/proyecto/ejemplos/4' },
          { title: 'GamerHub - Red Social de Gamers', link: '/proyecto/ejemplos/5' },
          { title: 'TravelDiaries - Red de Viajeros', link: '/proyecto/ejemplos/6' },
          { title: 'CodeLearning - Plataforma de Cursos', link: '/proyecto/ejemplos/7' },
          { title: 'JobMatch - Portal de Empleo', link: '/proyecto/ejemplos/8' },
          { title: 'ExpenseSplitter - Gestor de Gastos', link: '/proyecto/ejemplos/9' },
          { title: 'TaskFlow - Gestor de Proyectos', link: '/proyecto/ejemplos/10' },
          { title: 'RecipeShare - Red de Recetas', link: '/proyecto/ejemplos/11' },
          { title: 'PetCare - Red Social de Mascotas', link: '/proyecto/ejemplos/12' },
        ]},
    ],
    lessons: [
      { title: 'Definición del Proyecto', link: '/proyecto/planificacion/definicion' },
      { title: 'Requisitos y Especificaciones', link: '/proyecto/planificacion/requisitos' },
      { title: 'Arquitectura y Diseño', link: '/proyecto/planificacion/arquitectura' },
      { title: 'Ejemplos de Proyectos TFC', link: '/proyecto/planificacion/ejemplos' },
      { title: 'Agile y SCRUM', link: '/proyecto/metodologia/agile-scrum' },
      { title: 'Sprint 1', link: '/proyecto/metodologia/sprint-1' },
      { title: 'Sprint 2', link: '/proyecto/metodologia/sprint-2' },
      { title: 'Setup del Proyecto', link: '/proyecto/desarrollo/setup' },
      { title: 'Desarrollo Backend', link: '/proyecto/desarrollo/backend' },
      { title: 'Base de Datos', link: '/proyecto/desarrollo/database' },
      { title: 'APIs REST', link: '/proyecto/desarrollo/apis' },
      { title: 'Testing Unitario', link: '/proyecto/testing/unitario' },
      { title: 'Testing de Integración', link: '/proyecto/testing/integracion' },
      { title: 'Validación Final', link: '/proyecto/testing/validacion' },
      { title: 'Empaquetado y Build', link: '/proyecto/despliegue/build' },
      { title: 'Documentación', link: '/proyecto/despliegue/documentacion' },
      { title: 'Despliegue en Cloud', link: '/proyecto/despliegue/cloud' },
      { title: 'REPTE 1: Especificación del Proyecto', link: '/proyecto/retos/1' },
      { title: 'REPTE 2: Especificación de Requisitos', link: '/proyecto/retos/2' },
      { title: 'REPTE 3: Diseño de Arquitectura y BD', link: '/proyecto/retos/3' },
      { title: 'REPTE 4: Prototipo y Diseño Visual', link: '/proyecto/retos/4' },
      { title: 'REPTE 5: Configuración Agile/SCRUM', link: '/proyecto/retos/5' },
      { title: 'REPTE 6: Primer Sprint Development', link: '/proyecto/retos/6' },
      { title: 'REPTE 7: Second Sprint Development', link: '/proyecto/retos/7' },
      { title: 'REPTE 8: Final Sprint & Deployment', link: '/proyecto/retos/8' },
      { title: 'LibroHub - Marketplace de Libros Usados', link: '/proyecto/ejemplos/1' },
      { title: 'SportGear - E-commerce de Equipamiento', link: '/proyecto/ejemplos/2' },
      { title: 'ClinicaPro - Gestión de Clínica Médica', link: '/proyecto/ejemplos/3' },
      { title: 'PropertyHub - Plataforma de Alquiler', link: '/proyecto/ejemplos/4' },
      { title: 'GamerHub - Red Social de Gamers', link: '/proyecto/ejemplos/5' },
      { title: 'TravelDiaries - Red de Viajeros', link: '/proyecto/ejemplos/6' },
      { title: 'CodeLearning - Plataforma de Cursos', link: '/proyecto/ejemplos/7' },
      { title: 'JobMatch - Portal de Empleo', link: '/proyecto/ejemplos/8' },
      { title: 'ExpenseSplitter - Gestor de Gastos', link: '/proyecto/ejemplos/9' },
      { title: 'TaskFlow - Gestor de Proyectos', link: '/proyecto/ejemplos/10' },
      { title: 'RecipeShare - Red de Recetas', link: '/proyecto/ejemplos/11' },
      { title: 'PetCare - Red Social de Mascotas', link: '/proyecto/ejemplos/12' },
    ]},
  {
    id: 'metodologias',
    name: 'Metodologías & Procesos',
    description: 'Prácticas, metodologías y procesos para desarrollo profesional',
    landingPage: '/metodologias',
    sections: [
      {
        id: 'agile-scrum',
        name: 'Agile/SCRUM',
        fullName: 'Metodología Agile y SCRUM',
        description: 'Metodología ágil para gestión de proyectos iterativos',
        lessons: [
          { title: 'Introducción a Agile', link: '/metodologias/agile-scrum/introduccion' },
          { title: 'SCRUM Framework', link: '/metodologias/agile-scrum/scrum' },
          { title: 'Sprints y Planning', link: '/metodologias/agile-scrum/sprints' },
        ]},
      {
        id: 'clean-code',
        name: 'Clean Code',
        fullName: 'Código Limpio y Mantenible',
        description: 'Principios y prácticas para escribir código de calidad',
        lessons: [
          { title: 'Nombres Significativos', link: '/metodologias/clean-code/nombres' },
          { title: 'Funciones Limpias', link: '/metodologias/clean-code/funciones' },
          { title: 'Estructura y Formato', link: '/metodologias/clean-code/estructura' },
          { title: 'SOLID y Refactorización', link: '/metodologias/clean-code/solid' },
          { title: 'Patrones de Diseño', link: '/metodologias/clean-code/patrones' },
          { title: 'Antipatrones: Qué NO Hacer', link: '/metodologias/clean-code/antipatrones' },
        ]},
      {
        id: 'testing',
        name: 'Testing',
        fullName: 'Pruebas de Software',
        description: 'Estrategias y tipos de testing para garantizar calidad',
        lessons: [
          { title: 'Testing Unitario', link: '/metodologias/testing/unitario' },
          { title: 'Testing de Integración', link: '/metodologias/testing/integracion' },
          { title: 'Testing de Aceptación', link: '/metodologias/testing/aceptacion' },
        ]},
      {
        id: 'devops',
        name: 'DevOps',
        fullName: 'DevOps y CI/CD',
        description: 'Prácticas para automatización, integración y despliegue continuo',
        lessons: [
          { title: 'Introducción a DevOps', link: '/metodologias/devops/introduccion' },
          { title: 'CI/CD Pipelines', link: '/metodologias/devops/cicd' },
          { title: 'Monitoreo y Logs', link: '/metodologias/devops/monitoreo' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Agile', link: '/metodologias/agile-scrum/introduccion' },
      { title: 'SCRUM Framework', link: '/metodologias/agile-scrum/scrum' },
      { title: 'Sprints y Planning', link: '/metodologias/agile-scrum/sprints' },
      { title: 'Nombres Significativos', link: '/metodologias/clean-code/nombres' },
      { title: 'Funciones Limpias', link: '/metodologias/clean-code/funciones' },
      { title: 'Estructura y Formato', link: '/metodologias/clean-code/estructura' },
      { title: 'SOLID y Refactorización', link: '/metodologias/clean-code/solid' },
      { title: 'Patrones de Diseño', link: '/metodologias/clean-code/patrones' },
      { title: 'Antipatrones: Qué NO Hacer', link: '/metodologias/clean-code/antipatrones' },
      { title: 'Testing Unitario', link: '/metodologias/testing/unitario' },
      { title: 'Testing de Integración', link: '/metodologias/testing/integracion' },
      { title: 'Testing de Aceptación', link: '/metodologias/testing/aceptacion' },
      { title: 'Introducción a DevOps', link: '/metodologias/devops/introduccion' },
      { title: 'CI/CD Pipelines', link: '/metodologias/devops/cicd' },
      { title: 'Monitoreo y Logs', link: '/metodologias/devops/monitoreo' },
    ]},
  {
    id: 'mongodb',
    name: 'MongoDB - NoSQL',
    description: 'Bases de datos NoSQL flexibles, documentos JSON',
    landingPage: '/datos/mongodb',
    sections: [
      {
        id: 'introduccion',
        name: 'Introducción',
        description: 'Qué es MongoDB, conceptos clave y ventajas',
        lessons: [
          { title: 'Introducción a MongoDB y NoSQL', link: '/datos/mongodb/introduccion' },
          { title: 'MongoDB vs SQL - Comparativa', link: '/datos/mongodb/comparativa' },
          { title: 'Documentos y Colecciones', link: '/datos/mongodb/documentos' },
        ]},
      {
        id: 'operaciones',
        name: 'Operaciones Básicas',
        description: 'CRUD: Create, Read, Update, Delete en MongoDB',
        lessons: [
          { title: 'Insertar Documentos (Create)', link: '/datos/mongodb/operaciones/create' },
          { title: 'Consultar Documentos (Read)', link: '/datos/mongodb/operaciones/read' },
          { title: 'Actualizar Documentos (Update)', link: '/datos/mongodb/operaciones/update' },
          { title: 'Eliminar Documentos (Delete)', link: '/datos/mongodb/operaciones/delete' },
        ]},
      {
        id: 'consultas',
        name: 'Consultas Avanzadas',
        description: 'Filtros, proyecciones, agregaciones y búsquedas complejas',
        lessons: [
          { title: 'Filtros y Operadores de Consulta', link: '/datos/mongodb/consultas/filtros' },
          { title: 'Agregación con Pipeline', link: '/datos/mongodb/consultas/agregacion' },
          { title: 'Indexación y Optimización', link: '/datos/mongodb/consultas/indexacion' },
        ]},
      {
        id: 'modelado',
        name: 'Modelado de Datos',
        description: 'Esquemas, relaciones y buenas prácticas en MongoDB',
        lessons: [
          { title: 'Esquemas en MongoDB', link: '/datos/mongodb/modelado/esquemas' },
          { title: 'Relaciones: Embedding vs Referencing', link: '/datos/mongodb/modelado/relaciones' },
          { title: 'Validación de Documentos', link: '/datos/mongodb/modelado/validacion' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a MongoDB y NoSQL', link: '/datos/mongodb/introduccion' },
      { title: 'MongoDB vs SQL - Comparativa', link: '/datos/mongodb/comparativa' },
      { title: 'Documentos y Colecciones', link: '/datos/mongodb/documentos' },
      { title: 'Insertar Documentos (Create)', link: '/datos/mongodb/operaciones/create' },
      { title: 'Consultar Documentos (Read)', link: '/datos/mongodb/operaciones/read' },
      { title: 'Actualizar Documentos (Update)', link: '/datos/mongodb/operaciones/update' },
      { title: 'Eliminar Documentos (Delete)', link: '/datos/mongodb/operaciones/delete' },
      { title: 'Filtros y Operadores de Consulta', link: '/datos/mongodb/consultas/filtros' },
      { title: 'Agregación con Pipeline', link: '/datos/mongodb/consultas/agregacion' },
      { title: 'Indexación y Optimización', link: '/datos/mongodb/consultas/indexacion' },
      { title: 'Esquemas en MongoDB', link: '/datos/mongodb/modelado/esquemas' },
      { title: 'Relaciones: Embedding vs Referencing', link: '/datos/mongodb/modelado/relaciones' },
      { title: 'Validación de Documentos', link: '/datos/mongodb/modelado/validacion' },
    ]},
  {
    id: 'ia',
    name: 'Inteligencia Artificial',
    description: 'Desde IA generativa básica hasta agentes autónomos empresariales. 3 rutas de aprendizaje.',
    landingPage: '/ia',
    sections: [
      {
        id: 'basico-ia-generativa',
        name: '🟢 Básico: IA Generativa',
        fullName: 'Aprendizaje Básico: IA Generativa',
        description: 'Fundamentos de IA, APIs de Claude y OpenAI, Prompt Engineering. Ideal para iniciarse.',
        lessons: [
          { title: 'Qué es la IA generativa y para qué sirve', link: '/ia/basico/fundamentos/que-es-ia-generativa' },
          { title: 'Modelos de Lenguaje (LLMs): cómo funcionan', link: '/ia/basico/fundamentos/modelos-lenguaje-llms' },
          { title: 'IA vs Machine Learning vs Deep Learning', link: '/ia/basico/fundamentos/ia-vs-ml-vs-deep-learning' },
          { title: 'Claude API: primeros pasos', link: '/ia/basico/apis/claude-api-primeros-pasos' },
          { title: 'OpenAI API: primeros pasos', link: '/ia/basico/apis/openai-api-primeros-pasos' },
          { title: 'Autenticación y gestión de API Keys', link: '/ia/basico/apis/autenticacion-api-keys' },
          { title: 'Manejo de respuestas y streaming', link: '/ia/basico/apis/respuestas-streaming' },
          { title: 'Fundamentos de Prompt Engineering', link: '/ia/basico/prompt-engineering/fundamentos-prompt-engineering' },
          { title: 'Técnicas avanzadas de prompting', link: '/ia/basico/prompt-engineering/tecnicas-avanzadas-prompting' },
          { title: 'System prompts y roles', link: '/ia/basico/prompt-engineering/system-prompts-roles' },
          { title: 'Construir un chatbot con IA', link: '/ia/basico/casos-practicos/construir-chatbot' },
          { title: 'RAG (Retrieval-Augmented Generation) básico', link: '/ia/basico/casos-practicos/rag-basico' },
          { title: 'Automatización de tareas con IA', link: '/ia/basico/casos-practicos/automatizacion-tareas' },
        ]},
      {
        id: 'intermedio-agentes',
        name: '🟡 Intermedio: Agentes',
        fullName: 'Aprendizaje Intermedio: Agentes Inteligentes',
        description: 'Construye agentes autónomos que razonan y actúan. OpenClaw, Hermes, orquestación.',
        lessons: [
          { title: 'Fundamentos de Agentes de IA', link: '/ia/intermedio/agentes/fundamentos-agentes' },
          { title: 'Arquitectura de un Agente: 7 Pilares', link: '/ia/intermedio/agentes/arquitectura-agente' },
          { title: 'OpenClaw: Asistente en Tiempo Real', link: '/ia/intermedio/agentes/openclaw-realtime' },
          { title: 'Hermes: Orquestación Agéntica Completa', link: '/ia/intermedio/agentes/hermes-orquestacion' },
          { title: 'Comparativa: OpenClaw vs Hermes vs Otros', link: '/ia/intermedio/agentes/comparativa-herramientas' },
          { title: 'Construcción Paso a Paso de un Agente', link: '/ia/intermedio/agentes/construir-agente' },
          { title: 'Manejo de Errores y Reintentos', link: '/ia/intermedio/agentes/errores-reintentos' },
          { title: 'Caso Práctico: Agente de Atención al Cliente', link: '/ia/intermedio/agentes/caso-practico-soporte' },
        ]},
      {
        id: 'avanzado-enterprise',
        name: '🔴 Avanzado: Enterprise',
        fullName: 'Aprendizaje Avanzado: IA en Producción',
        description: 'Despliegue, configuración avanzada, MCP, memory. Producción enterprise-ready.',
        lessons: [
          { title: 'Guía de Inicio Rápido: Instalación y Setup', link: '/ia/avanzado/enterprise/quick-start-agentes' },
          { title: 'Configuración Avanzada: soul.md y Personalización', link: '/ia/avanzado/enterprise/configuracion-soul' },
          { title: 'Gestión de Memoria: memory.md y Persistencia', link: '/ia/avanzado/enterprise/gestion-memoria' },
          { title: 'Model Context Protocol (MCP): Integraciones Avanzadas', link: '/ia/avanzado/enterprise/mcp-protocol' },
          { title: 'FAQ Técnica Completa: Tokens, Seguridad, Arquitectura', link: '/ia/avanzado/enterprise/faq-tecnica' },
          { title: 'Despliegue en Producción: Docker, Monitoreo, Escala', link: '/ia/avanzado/enterprise/despliegue-produccion' },
        ]},
    ],
    lessons: [
      { title: 'Qué es la IA generativa y para qué sirve', link: '/ia/basico/fundamentos/que-es-ia-generativa' },
      { title: 'Modelos de Lenguaje (LLMs): cómo funcionan', link: '/ia/basico/fundamentos/modelos-lenguaje-llms' },
      { title: 'IA vs Machine Learning vs Deep Learning', link: '/ia/basico/fundamentos/ia-vs-ml-vs-deep-learning' },
      { title: 'Claude API: primeros pasos', link: '/ia/basico/apis/claude-api-primeros-pasos' },
      { title: 'OpenAI API: primeros pasos', link: '/ia/basico/apis/openai-api-primeros-pasos' },
      { title: 'Autenticación y gestión de API Keys', link: '/ia/basico/apis/autenticacion-api-keys' },
      { title: 'Manejo de respuestas y streaming', link: '/ia/basico/apis/respuestas-streaming' },
      { title: 'Fundamentos de Prompt Engineering', link: '/ia/basico/prompt-engineering/fundamentos-prompt-engineering' },
      { title: 'Técnicas avanzadas de prompting', link: '/ia/basico/prompt-engineering/tecnicas-avanzadas-prompting' },
      { title: 'System prompts y roles', link: '/ia/basico/prompt-engineering/system-prompts-roles' },
      { title: 'Construir un chatbot con IA', link: '/ia/basico/casos-practicos/construir-chatbot' },
      { title: 'RAG (Retrieval-Augmented Generation) básico', link: '/ia/basico/casos-practicos/rag-basico' },
      { title: 'Automatización de tareas con IA', link: '/ia/basico/casos-practicos/automatizacion-tareas' },
      { title: 'Fundamentos de Agentes de IA', link: '/ia/intermedio/agentes/fundamentos-agentes' },
      { title: 'Arquitectura de un Agente: 7 Pilares', link: '/ia/intermedio/agentes/arquitectura-agente' },
      { title: 'OpenClaw: Asistente en Tiempo Real', link: '/ia/intermedio/agentes/openclaw-realtime' },
      { title: 'Hermes: Orquestación Agéntica Completa', link: '/ia/intermedio/agentes/hermes-orquestacion' },
      { title: 'Comparativa: OpenClaw vs Hermes vs Otros', link: '/ia/intermedio/agentes/comparativa-herramientas' },
      { title: 'Construcción Paso a Paso de un Agente', link: '/ia/intermedio/agentes/construir-agente' },
      { title: 'Manejo de Errores y Reintentos', link: '/ia/intermedio/agentes/errores-reintentos' },
      { title: 'Caso Práctico: Agente de Atención al Cliente', link: '/ia/intermedio/agentes/caso-practico-soporte' },
      { title: 'Guía de Inicio Rápido: Instalación y Setup', link: '/ia/avanzado/enterprise/quick-start-agentes' },
      { title: 'Configuración Avanzada: soul.md y Personalización', link: '/ia/avanzado/enterprise/configuracion-soul' },
      { title: 'Gestión de Memoria: memory.md y Persistencia', link: '/ia/avanzado/enterprise/gestion-memoria' },
      { title: 'Model Context Protocol (MCP): Integraciones Avanzadas', link: '/ia/avanzado/enterprise/mcp-protocol' },
      { title: 'FAQ Técnica Completa: Tokens, Seguridad, Arquitectura', link: '/ia/avanzado/enterprise/faq-tecnica' },
      { title: 'Despliegue en Producción: Docker, Monitoreo, Escala', link: '/ia/avanzado/enterprise/despliegue-produccion' },
    ]},
  {
    id: 'ciberseguridad',
    name: 'Ciberseguridad',
    description: 'Fundamentos de seguridad web, OWASP Top 10, autenticación segura y buenas prácticas de ciberseguridad para desarrolladores',
    landingPage: '/ciberseguridad',
    sections: [
      {
        id: 'fundamentos',
        name: 'Fundamentos de Ciberseguridad',
        description: 'Qué es la ciberseguridad, los principios CIA y los tipos de amenazas más comunes',
        lessons: [
          { title: 'Qué es la ciberseguridad y por qué importa en desarrollo web', link: '/ciberseguridad/fundamentos/que-es-ciberseguridad' },
          { title: 'Principios CIA: Confidencialidad, Integridad, Disponibilidad', link: '/ciberseguridad/fundamentos/principios-cia' },
          { title: 'Tipos de amenazas y vectores de ataque comunes', link: '/ciberseguridad/fundamentos/tipos-amenazas-vectores-ataque' },
        ]},
      {
        id: 'owasp',
        name: 'Seguridad Web: OWASP Top 10',
        description: 'Introducción al OWASP Top 10 y las vulnerabilidades web más frecuentes: inyección SQL, XSS y CSRF',
        lessons: [
          { title: 'OWASP Top 10: introducción y visión general', link: '/ciberseguridad/owasp/owasp-top-10-introduccion' },
          { title: 'Inyección SQL: cómo prevenirla', link: '/ciberseguridad/owasp/inyeccion-sql-prevencion' },
          { title: 'XSS (Cross-Site Scripting)', link: '/ciberseguridad/owasp/xss-cross-site-scripting' },
          { title: 'CSRF (Cross-Site Request Forgery)', link: '/ciberseguridad/owasp/csrf-cross-site-request-forgery' },
        ]},
      {
        id: 'autenticacion',
        name: 'Autenticación y Comunicación Segura',
        description: 'Autenticación, autorización, JWT, HTTPS/TLS y gestión segura de contraseñas',
        lessons: [
          { title: 'Autenticación y Autorización: conceptos clave', link: '/ciberseguridad/autenticacion/autenticacion-autorizacion' },
          { title: 'JWT: tokens seguros', link: '/ciberseguridad/autenticacion/jwt-tokens-seguros' },
          { title: 'HTTPS y TLS: cómo funciona', link: '/ciberseguridad/autenticacion/https-tls-funcionamiento' },
          { title: 'Gestión segura de contraseñas (hashing, bcrypt, salts)', link: '/ciberseguridad/autenticacion/gestion-segura-contrasenas' },
        ]},
      {
        id: 'buenas-practicas',
        name: 'Buenas Prácticas y Herramientas',
        description: 'Sanitización de inputs, gestión de secretos y checklist de seguridad para APIs REST en producción',
        lessons: [
          { title: 'Sanitización y validación de inputs', link: '/ciberseguridad/buenas-practicas/sanitizacion-validacion-inputs' },
          { title: 'Gestión de secretos y variables de entorno', link: '/ciberseguridad/buenas-practicas/gestion-secretos-variables-entorno' },
          { title: 'Seguridad en APIs REST y checklist de producción', link: '/ciberseguridad/buenas-practicas/seguridad-apis-rest-checklist' },
        ]},
    ],
    lessons: [
      { title: 'Qué es la ciberseguridad y por qué importa en desarrollo web', link: '/ciberseguridad/fundamentos/que-es-ciberseguridad' },
      { title: 'Principios CIA: Confidencialidad, Integridad, Disponibilidad', link: '/ciberseguridad/fundamentos/principios-cia' },
      { title: 'Tipos de amenazas y vectores de ataque comunes', link: '/ciberseguridad/fundamentos/tipos-amenazas-vectores-ataque' },
      { title: 'OWASP Top 10: introducción y visión general', link: '/ciberseguridad/owasp/owasp-top-10-introduccion' },
      { title: 'Inyección SQL: cómo prevenirla', link: '/ciberseguridad/owasp/inyeccion-sql-prevencion' },
      { title: 'XSS (Cross-Site Scripting)', link: '/ciberseguridad/owasp/xss-cross-site-scripting' },
      { title: 'CSRF (Cross-Site Request Forgery)', link: '/ciberseguridad/owasp/csrf-cross-site-request-forgery' },
      { title: 'Autenticación y Autorización: conceptos clave', link: '/ciberseguridad/autenticacion/autenticacion-autorizacion' },
      { title: 'JWT: tokens seguros', link: '/ciberseguridad/autenticacion/jwt-tokens-seguros' },
      { title: 'HTTPS y TLS: cómo funciona', link: '/ciberseguridad/autenticacion/https-tls-funcionamiento' },
      { title: 'Gestión segura de contraseñas (hashing, bcrypt, salts)', link: '/ciberseguridad/autenticacion/gestion-segura-contrasenas' },
      { title: 'Sanitización y validación de inputs', link: '/ciberseguridad/buenas-practicas/sanitizacion-validacion-inputs' },
      { title: 'Gestión de secretos y variables de entorno', link: '/ciberseguridad/buenas-practicas/gestion-secretos-variables-entorno' },
      { title: 'Seguridad en APIs REST y checklist de producción', link: '/ciberseguridad/buenas-practicas/seguridad-apis-rest-checklist' },
    ]},
  {
    id: 'html',
    name: 'HTML',
    description: 'Estructura y semántica de documentos web',
    landingPage: '/frontend/html',
    sections: [
      {
        id: 'introduccion',
        name: 'Introducción',
        description: 'Conceptos básicos de HTML',
        lessons: [
          { title: 'Introducción a HTML', link: '/frontend/html/introduccion' },
          { title: 'Estructura básica de un documento', link: '/frontend/html/estructura' },
          { title: 'Etiquetas y elementos', link: '/frontend/html/etiquetas' },
        ]},
      {
        id: 'formularios',
        name: 'Formularios',
        description: 'Creación y validación de formularios',
        lessons: [
          { title: 'Formularios HTML', link: '/frontend/html/formularios' },
          { title: 'Validación de formularios', link: '/frontend/html/validacion' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a HTML', link: '/frontend/html/introduccion' },
      { title: 'Estructura básica de un documento', link: '/frontend/html/estructura' },
      { title: 'Etiquetas y elementos', link: '/frontend/html/etiquetas' },
      { title: 'Formularios HTML', link: '/frontend/html/formularios' },
      { title: 'Validación de formularios', link: '/frontend/html/validacion' },
    ]},
  {
    id: 'css',
    name: 'CSS',
    description: 'Estilos, layouts y diseño responsivo',
    landingPage: '/frontend/css',
    sections: [
      {
        id: 'introduccion',
        name: 'Fundamentos',
        description: 'Conceptos básicos de CSS',
        lessons: [
          { title: 'Introducción a CSS', link: '/frontend/css/introduccion' },
          { title: 'Selectores y propiedades', link: '/frontend/css/selectores' },
          { title: 'Modelo de caja (Box Model)', link: '/frontend/css/box-model' },
        ]},
      {
        id: 'layouts',
        name: 'Layouts',
        description: 'Flexbox, Grid y posicionamiento',
        lessons: [
          { title: 'Flexbox - Layouts flexibles', link: '/frontend/css/flexbox' },
          { title: 'CSS Grid - Layouts avanzados', link: '/frontend/css/grid' },
          { title: 'Diseño responsivo', link: '/frontend/css/responsive' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a CSS', link: '/frontend/css/introduccion' },
      { title: 'Selectores y propiedades', link: '/frontend/css/selectores' },
      { title: 'Modelo de caja (Box Model)', link: '/frontend/css/box-model' },
      { title: 'Flexbox - Layouts flexibles', link: '/frontend/css/flexbox' },
      { title: 'CSS Grid - Layouts avanzados', link: '/frontend/css/grid' },
      { title: 'Diseño responsivo', link: '/frontend/css/responsive' },
    ]},
  {
    id: 'react',
    name: 'React',
    description: 'Biblioteca para construir interfaces de usuario',
    landingPage: '/frontend/react',
    sections: [
      {
        id: 'fundamentos',
        name: 'Fundamentos',
        description: 'Conceptos básicos de React',
        lessons: [
          { title: 'Introducción a React', description: 'Qué es React, por qué usarlo y cómo funciona la biblioteca', link: '/frontend/react/fundamentos/introduccion' },
          { title: 'JSX y Componentes', description: 'Aprende JSX, componentes funcionales y cómo organizar tu código', link: '/frontend/react/fundamentos/jsx-componentes' },
          { title: 'Props y Estado', description: 'Cómo pasar datos entre componentes y gestionar el estado interno', link: '/frontend/react/fundamentos/props-estado' },
        ]},
      {
        id: 'hooks',
        name: 'Hooks',
        description: 'useState, useEffect y hooks personalizados',
        lessons: [
          { title: 'useState Hook', description: 'Gestiona estado en componentes funcionales con useState', link: '/frontend/react/hooks/usestate' },
          { title: 'useEffect Hook', description: 'Ejecuta efectos secundarios y ciclos de vida con useEffect', link: '/frontend/react/hooks/useeffect' },
          { title: 'Hooks personalizados', description: 'Crea tus propios hooks reutilizables', link: '/frontend/react/hooks/custom' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a React', link: '/frontend/react/fundamentos/introduccion' },
      { title: 'JSX y Componentes', link: '/frontend/react/fundamentos/jsx-componentes' },
      { title: 'Props y Estado', link: '/frontend/react/fundamentos/props-estado' },
      { title: 'useState Hook', link: '/frontend/react/hooks/usestate' },
      { title: 'useEffect Hook', link: '/frontend/react/hooks/useeffect' },
      { title: 'Hooks personalizados', link: '/frontend/react/hooks/custom' },
    ]},
  {
    id: 'angular',
    name: 'Angular',
    description: 'Framework completo para aplicaciones web',
    landingPage: '/frontend/angular',
    sections: [
      {
        id: 'fundamentos',
        name: 'Fundamentos',
        description: 'Conceptos básicos de Angular',
        lessons: [
          { title: 'Introducción a Angular', link: '/frontend/angular/introduccion' },
          { title: 'Componentes y Templates', link: '/frontend/angular/componentes' },
          { title: 'Data Binding', link: '/frontend/angular/data-binding' },
        ]},
      {
        id: 'servicios',
        name: 'Servicios',
        description: 'Servicios y inyección de dependencias',
        lessons: [
          { title: 'Servicios en Angular', link: '/frontend/angular/servicios' },
          { title: 'Inyección de dependencias', link: '/frontend/angular/dependency-injection' },
          { title: 'HttpClient y APIs', link: '/frontend/angular/httpclient' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Angular', link: '/frontend/angular/introduccion' },
      { title: 'Componentes y Templates', link: '/frontend/angular/componentes' },
      { title: 'Data Binding', link: '/frontend/angular/data-binding' },
      { title: 'Servicios en Angular', link: '/frontend/angular/servicios' },
      { title: 'Inyección de dependencias', link: '/frontend/angular/dependency-injection' },
      { title: 'HttpClient y APIs', link: '/frontend/angular/httpclient' },
    ]},
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    description: 'Framework CSS para diseño responsivo',
    landingPage: '/frontend/bootstrap',
    sections: [
      {
        id: 'introduccion',
        name: 'Introducción',
        description: 'Conceptos básicos de Bootstrap',
        lessons: [
          { title: 'Introducción a Bootstrap', link: '/frontend/bootstrap/introduccion' },
          { title: 'Sistema de Grid', link: '/frontend/bootstrap/grid' },
          { title: 'Componentes básicos', link: '/frontend/bootstrap/componentes' },
        ]},
      {
        id: 'componentes',
        name: 'Componentes',
        description: 'Componentes de Bootstrap',
        lessons: [
          { title: 'Botones y formularios', link: '/frontend/bootstrap/botones-formularios' },
          { title: 'Navbars y menús', link: '/frontend/bootstrap/navbars' },
          { title: 'Cards y layouts', link: '/frontend/bootstrap/cards' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Bootstrap', link: '/frontend/bootstrap/introduccion' },
      { title: 'Sistema de Grid', link: '/frontend/bootstrap/grid' },
      { title: 'Componentes básicos', link: '/frontend/bootstrap/componentes' },
      { title: 'Botones y formularios', link: '/frontend/bootstrap/botones-formularios' },
      { title: 'Navbars y menús', link: '/frontend/bootstrap/navbars' },
      { title: 'Cards y layouts', link: '/frontend/bootstrap/cards' },
    ]},
  {
    id: 'tailwindcss',
    name: 'Tailwind CSS',
    description: 'Framework utility-first para estilos CSS',
    landingPage: '/frontend/tailwindcss',
    sections: [
      {
        id: 'introduccion',
        name: 'Introducción',
        description: 'Conceptos básicos de Tailwind CSS',
        lessons: [
          { title: 'Introducción a Tailwind CSS', link: '/frontend/tailwindcss/introduccion' },
          { title: 'Utility Classes', link: '/frontend/tailwindcss/utilities' },
          { title: 'Responsive Design', link: '/frontend/tailwindcss/responsive' },
        ]},
      {
        id: 'componentes',
        name: 'Componentes',
        description: 'Construcción de componentes con Tailwind',
        lessons: [
          { title: 'Creación de componentes', link: '/frontend/tailwindcss/componentes' },
          { title: 'Customización', link: '/frontend/tailwindcss/customizacion' },
          { title: 'Temas y configuración', link: '/frontend/tailwindcss/temas' },
        ]},
    ],
    lessons: [
      { title: 'Introducción a Tailwind CSS', link: '/frontend/tailwindcss/introduccion' },
      { title: 'Utility Classes', link: '/frontend/tailwindcss/utilities' },
      { title: 'Responsive Design', link: '/frontend/tailwindcss/responsive' },
      { title: 'Creación de componentes', link: '/frontend/tailwindcss/componentes' },
      { title: 'Customización', link: '/frontend/tailwindcss/customizacion' },
      { title: 'Temas y configuración', link: '/frontend/tailwindcss/temas' },
    ]}
];

/**
 * Mapa de módulos para O(1) lookup en lugar de O(n) .find()
 * Mejora performance en landing pages (50-100ms por navegación × 25 páginas)
 */
export const moduleMap = new Map(modulesWithLessons.map(m => [m.id, m]));

/**
 * Helper para obtener un módulo por ID - O(1) en lugar de O(n)
 * @param {string} moduleId - ID del módulo (ej: 'aws', 'docker', 'java')
 * @returns {object} El módulo completo o undefined
 */
export const getModule = (moduleId) => moduleMap.get(moduleId);

/**
 * Obtener la primera lección de una sección del módulo
 * Usado para redirigir cuando clicas en una sección en ModuleSwitch
 * @param {string} moduleId - ID del módulo (ej: 'java')
 * @param {string} sectionId - ID de la sección (ej: 'introduccion', 'oop')
 * @returns {string|null} Link a la primera lección o null si no existe
 */
export const getFirstLessonOfSection = (moduleId, sectionId) => {
  const module = getModule(moduleId);
  if (!module || !module.sections) return null;

  const section = module.sections.find(s => s.id === sectionId);
  if (!section || !section.lessons || section.lessons.length === 0) return null;

  return section.lessons[0].link;
};
