/**
 * Configuración completa de módulos con lecciones y secciones
 * Ruta: Git → Java → SQL → Spring Boot
 */
import gitLogoImg from '../assets/images/logos/git-logo.png';
import blancaJavaImg from '../assets/images/header/blancajava.jpeg';

export const modulesWithLessons = [
  {
    id: 'aws',
    name: 'Amazon Web Services',
    icon: '☁️',
    description: 'Servicios en la nube: EC2, RDS, S3, Lambda y despliegue profesional',
    landingPage: '/aws/landing',
    sections: [
      {
        id: 'fundamentales',
        name: 'Fundamentales',
        icon: '📖',
        description: 'Qué es AWS, conceptos clave, cuenta, IAM y pricing',
        lessons: [
          { title: 'Qué es AWS y por qué usarlo', link: '/aws/fundamentales/intro', icon: '☁️' },
          { title: 'Arquitectura de Software y Proveedores Cloud', link: '/aws/fundamentales/arquitectura', icon: '🏗️' },
          { title: 'Conceptos Clave: Regiones, AZ, VPC', link: '/aws/fundamentales/conceptos', icon: '🗺️' },
          { title: 'Gestión de Identidad y Acceso (IAM)', link: '/aws/fundamentales/iam', icon: '🔐' },
          { title: 'Pricing y Estimador de Costos', link: '/aws/fundamentales/pricing', icon: '💰' },
        ],
      },
      {
        id: 'servicios',
        name: 'Servicios Principales',
        icon: '⚙️',
        description: 'Servicios más usados: EC2, RDS, S3, Lambda, DynamoDB',
        lessons: [
          { title: 'EC2 - Máquinas Virtuales', link: '/aws/servicios/ec2', icon: '🖥️' },
          { title: 'RDS - Bases de Datos Relacionales', link: '/aws/servicios/rds', icon: '🗄️' },
          { title: 'S3 - Almacenamiento de Objetos', link: '/aws/servicios/s3', icon: '📦' },
          { title: 'Lambda - Serverless Computing', link: '/aws/servicios/lambda', icon: '⚡' },
          { title: 'DynamoDB - Base de Datos NoSQL', link: '/aws/servicios/dynamodb', icon: '🔑' },
          { title: 'Almacenamiento (S3, EBS, EFS)', link: '/aws/servicios/almacenamiento', icon: '💾' },
        ],
      },
      {
        id: 'redes',
        name: 'Redes & Seguridad',
        icon: '🌐',
        description: 'VPC, Security Groups, Route Tables, conectividad',
        lessons: [
          { title: 'VPC - Redes Privadas en AWS', link: '/aws/redes/vpc', icon: '🌐' },
          { title: 'Security Groups & Firewalls', link: '/aws/operaciones/seguridad', icon: '🔐' },
        ],
      },
      {
        id: 'deployment',
        name: 'Deployment & CI/CD',
        icon: '🚀',
        description: 'Desplegar aplicaciones: CloudFormation, CodePipeline, Blue/Green, Contenedores',
        lessons: [
          { title: 'Despliegue e Infraestructura como Código (IaC)', link: '/aws/deployment/cicd', icon: '⚙️' },
          { title: 'Elastic Beanstalk - Deploy Simplificado', link: '/aws/deployment/beanstalk', icon: '🌱' },
          { title: 'ECS - Contenedores en AWS', link: '/aws/deployment/ecs', icon: '📦' },
          { title: 'CloudFront - CDN Global', link: '/aws/deployment/cloudfront', icon: '🌍' },
        ],
      },
      {
        id: 'operaciones',
        name: 'Operaciones & Seguridad',
        icon: '🔒',
        description: 'CloudWatch, Security Groups, Backup y mejores prácticas',
        lessons: [
          { title: 'CloudWatch - Monitoreo y Logs', link: '/aws/operaciones/cloudwatch', icon: '📊' },
          { title: 'Security Groups y VPC', link: '/aws/operaciones/seguridad', icon: '🔐' },
          { title: 'Backup y Recuperación', link: '/aws/operaciones/backup', icon: '💾' },
          { title: 'Mejores Prácticas en AWS', link: '/aws/operaciones/practicas', icon: '✅' },
        ],
      },
      {
        id: 'integracion',
        name: 'Integración & Lenguajes',
        icon: '🔗',
        description: 'Integración con Java, Spring Boot y SDKs',
        lessons: [
          { title: 'AWS SDK v2 con Java & Spring Boot', link: '/aws/integracion/java', icon: '☕' },
        ],
      },
      {
        id: 'proyecto',
        name: 'Proyecto Final',
        icon: '🎓',
        description: 'Arquitectura completa integrada del Laboratorio Guttman',
        lessons: [
          { title: 'Proyecto Final: Arquitectura del Laboratorio Guttman', link: '/aws/proyecto/final', icon: '🏆' },
        ],
      },
    ],
    lessons: [
      { title: 'Qué es AWS y por qué usarlo', link: '/aws/fundamentales/intro' },
      { title: 'Arquitectura de Software y Proveedores Cloud', link: '/aws/fundamentales/arquitectura' },
      { title: 'Conceptos Clave: Regiones, AZ, VPC', link: '/aws/fundamentales/conceptos' },
      { title: 'Gestión de Identidad y Acceso (IAM)', link: '/aws/fundamentales/iam' },
      { title: 'Pricing y Estimador de Costos', link: '/aws/fundamentales/pricing' },
      { title: 'EC2 - Máquinas Virtuales', link: '/aws/servicios/ec2' },
      { title: 'RDS - Bases de Datos Relacionales', link: '/aws/servicios/rds' },
      { title: 'S3 - Almacenamiento de Objetos', link: '/aws/servicios/s3' },
      { title: 'Lambda - Serverless Computing', link: '/aws/servicios/lambda' },
      { title: 'DynamoDB - Base de Datos NoSQL', link: '/aws/servicios/dynamodb' },
      { title: 'Almacenamiento (S3, EBS, EFS)', link: '/aws/servicios/almacenamiento' },
      { title: 'VPC - Redes Privadas en AWS', link: '/aws/redes/vpc' },
      { title: 'Despliegue e Infraestructura como Código', link: '/aws/deployment/cicd' },
      { title: 'Elastic Beanstalk - Deploy Simplificado', link: '/aws/deployment/beanstalk' },
      { title: 'ECS - Contenedores en AWS', link: '/aws/deployment/ecs' },
      { title: 'CloudFront - CDN Global', link: '/aws/deployment/cloudfront' },
      { title: 'CloudWatch - Monitoreo y Logs', link: '/aws/operaciones/cloudwatch' },
      { title: 'Security Groups y Firewalls', link: '/aws/operaciones/seguridad' },
      { title: 'Backup y Recuperación', link: '/aws/operaciones/backup' },
      { title: 'Mejores Prácticas en AWS', link: '/aws/operaciones/practicas' },
      { title: 'AWS SDK v2 con Java & Spring Boot', link: '/aws/integracion/java' },
      { title: 'Proyecto Final: Arquitectura del Laboratorio Guttman', link: '/aws/proyecto/final' },
    ],
  },
  {
    id: 'docker',
    name: 'Docker',
    icon: '🐳',
    description: 'Containerización, deployment y orquestación profesional',
    landingPage: '/docker/landing',
    sections: [
      {
        id: 'fundamentales',
        name: 'Fundamentales',
        icon: '📖',
        description: 'Aprende desde cero: qué es Docker, conceptos clave, tu primer contenedor y Dockerfile.',
        lessons: [
          { title: 'Qué es Docker y por qué lo necesitas', link: '/docker/fundamentales/intro', icon: '🐳' },
          { title: 'Conceptos: Imágenes, Contenedores, Volúmenes', link: '/docker/fundamentales/conceptos', icon: '📦' },
          { title: 'Tu primer Dockerfile', link: '/docker/fundamentales/dockerfile', icon: '📝' },
          { title: 'Comandos Esenciales de Docker', link: '/docker/fundamentales/comandos', icon: '⌨️' },
        ],
      },
      {
        id: 'composicion',
        name: 'Multi-Contenedor',
        icon: '🔗',
        description: 'Docker Compose, networking, comunicación entre contenedores y volúmenes avanzados.',
        lessons: [
          { title: 'Docker Compose: Orquestación', link: '/docker/composicion/compose', icon: '🔗' },
          { title: 'Networking y DNS Interno', link: '/docker/composicion/networking', icon: '🌐' },
          { title: 'Volúmenes: Persistencia de Datos', link: '/docker/composicion/volumenes', icon: '💾' },
        ],
      },
      {
        id: 'avanzado',
        name: 'Avanzado',
        icon: '⚡',
        description: 'Multi-stage builds, optimización, seguridad, debugging y mejores prácticas.',
        lessons: [
          { title: 'Multi-Stage Builds - Reducir Tamaño', link: '/docker/avanzado/multistage', icon: '⚙️' },
          { title: 'Optimización y Seguridad', link: '/docker/avanzado/optimizacion', icon: '🔒' },
          { title: 'Debugging y Troubleshooting', link: '/docker/avanzado/debugging', icon: '🔍' },
          { title: 'Buenas Prácticas', link: '/docker/avanzado/practicas', icon: '✅' },
        ],
      },
      {
        id: 'frameworks',
        name: 'Frameworks Populares',
        icon: '🚀',
        description: 'Dockerizar aplicaciones: Python/FastAPI, Java/Spring, Frontend/React, Node.js.',
        lessons: [
          { title: 'Backend: Python & FastAPI', link: '/docker/frameworks/python', icon: '🐍' },
          { title: 'Backend: Java & Spring Boot', link: '/docker/frameworks/java', icon: '☕' },
          { title: 'Frontend: React, Angular, Vue', link: '/docker/frameworks/frontend', icon: '⚛️' },
          { title: 'Node.js & Express', link: '/docker/frameworks/nodejs', icon: '📦' },
        ],
      },
    ],
    lessons: [
      { title: 'Introducción: Qué es Docker y por qué lo necesitas', link: '/docker/fundamentales/intro' },
      { title: 'Conceptos: Imágenes, Contenedores, Volúmenes y Capas', link: '/docker/fundamentales/conceptos' },
      { title: 'Tu primer Dockerfile - Instrucciones principales', link: '/docker/fundamentales/dockerfile' },
      { title: 'Comandos Esenciales de Docker - Build, Run, Logs', link: '/docker/fundamentales/comandos' },
      { title: 'Docker Compose: Orquestación de Múltiples Contenedores', link: '/docker/composicion/compose' },
      { title: 'Networking y DNS Interno entre Contenedores', link: '/docker/composicion/networking' },
      { title: 'Volúmenes: Persistencia de Datos (Named vs Bind)', link: '/docker/composicion/volumenes' },
      { title: 'Multi-Stage Builds - Reducir Tamaño de Imágenes', link: '/docker/avanzado/multistage' },
      { title: 'Optimización: Alpine, Caché, Seguridad', link: '/docker/avanzado/optimizacion' },
      { title: 'Debugging y Troubleshooting - Logs, Exec, Stats', link: '/docker/avanzado/debugging' },
      { title: 'Buenas Prácticas Profesionales y Checklist', link: '/docker/avanzado/practicas' },
      { title: 'Backend: Python & FastAPI en Docker', link: '/docker/frameworks/python' },
      { title: 'Backend: Java & Spring Boot Multi-Stage', link: '/docker/frameworks/java' },
      { title: 'Frontend: React, Angular, Vue - Multi-Stage', link: '/docker/frameworks/frontend' },
      { title: 'Node.js & Express - Alpine y Producción', link: '/docker/frameworks/nodejs' },
    ],
  },
  {
    id: 'git',
    name: 'Git',
    icon: gitLogoImg,
    description: 'Control de versiones y colaboración',
    landingPage: '/git/landing',
    sections: [
      {
        id: 'basicos',
        name: 'Git Básicos',
        icon: '📖',
        description: 'Domina los fundamentos: configuración, repositorios, commits, ramas y merge. Todo lo que necesitas para comenzar con Git.',
        lessons: [
          { title: 'Configuración inicial de Git', link: '/git/basicos/configuracion-inicial', icon: '⚙️' },
          { title: 'Crear y clonar repositorios', link: '/git/basicos/crear-clonar-repos', icon: '📁' },
          { title: 'Commits y mensajes claros', link: '/git/basicos/commits', icon: '💾' },
          { title: 'Ramas (branches)', link: '/git/basicos/branches', icon: '🌿' },
          { title: 'Merge y resolución de conflictos', link: '/git/basicos/merge', icon: '🔀' },
          { title: 'Configuración de Alias en Git', link: '/git/basicos/alias', icon: '⌨️' },
          { title: 'Errores Comunes en Git', link: '/git/basicos/errores-comunes', icon: '⚠️' },
        ],
      },
      {
        id: 'avanzado',
        name: 'Remoto y Colaboración',
        icon: '⚡',
        description: 'Sincronización remota, pull requests y plataformas colaborativas. Aprende a trabajar en equipo y gestionar proyectos profesionales.',
        lessons: [
          { title: 'Push, Pull y Fetch', link: '/git/avanzado/push-pull-fetch', icon: '⬆️' },
          { title: 'Pull requests y colaboración', link: '/git/avanzado/pull-requests', icon: '🤝' },
          { title: 'GitHub, GitLab y Bitbucket', link: '/git/avanzado/plataformas-remotas', icon: '🌐' },
          { title: 'Git Workflow y Conventional Commits', link: '/git/avanzado/workflow', icon: '📝' },
          { title: 'GitHub', link: '/git/avanzado/github', icon: '🐙' },
          { title: 'GitLab', link: '/git/avanzado/gitlab', icon: '🦊' },
          { title: 'Bitbucket', link: '/git/avanzado/bitbucket', icon: '🪣' },
        ],
      },
      {
        id: 'practicas',
        name: 'Prácticas con Git',
        icon: '💪',
        description: 'Ejercicios prácticos para poner en práctica lo aprendido. Realiza tareas reales de configuración y uso de Git.',
        lessons: [
          { title: 'Práctica: Configura tu Git', link: '/git/practicas/configura-tu-git', icon: '⚙️' },
          { title: 'Práctica: Crea tu Primer Repositorio', link: '/git/practicas/crea-tu-primer-repositorio', icon: '📁' },
          { title: 'Práctica: Haz tus Primeros Commits', link: '/git/practicas/haz-tus-primeros-commits', icon: '💾' },
          { title: 'Práctica: Trabaja con Ramas', link: '/git/practicas/trabaja-con-ramas', icon: '🌿' },
          { title: 'Práctica: Resuelve Conflictos de Merge', link: '/git/practicas/resuelve-conflictos-de-merge', icon: '🔀' },
        ],
      },
    ],
    lessons: [
      { title: 'Configuración inicial de Git', link: '/git/basicos/configuracion-inicial' },
      { title: 'Crear y clonar repositorios', link: '/git/basicos/crear-clonar-repos' },
      { title: 'Commits y mensajes claros', link: '/git/basicos/commits' },
      { title: 'Ramas (branches)', link: '/git/basicos/branches' },
      { title: 'Merge y resolución de conflictos', link: '/git/basicos/merge' },
      { title: 'Configuración de Alias en Git', link: '/git/basicos/alias' },
      { title: 'Errores Comunes en Git', link: '/git/basicos/errores-comunes' },
      { title: 'Push, Pull y Fetch', link: '/git/avanzado/push-pull-fetch' },
      { title: 'Pull requests y colaboración', link: '/git/avanzado/pull-requests' },
      { title: 'GitHub, GitLab y Bitbucket', link: '/git/avanzado/plataformas-remotas' },
      { title: 'Git Workflow y Conventional Commits', link: '/git/avanzado/workflow' },
      { title: 'GitHub', link: '/git/avanzado/github' },
      { title: 'GitLab', link: '/git/avanzado/gitlab' },
      { title: 'Bitbucket', link: '/git/avanzado/bitbucket' },
    ],
  },
  {
    id: 'java',
    name: 'Java',
    icon: '☕',
    description: 'Domina Java: desde fundamentos hasta patrones avanzados y persistencia de datos',
    landingPage: '/java/landing',
    sections: [
      {
        id: 'basico',
        name: 'Básico',
        fullName: 'Java Básico',
        icon: '📖',
        description: 'Fundamentos esenciales: tipos de datos, control de flujo, strings, arrays y excepciones.',
        lessons: [
          { title: 'Tipos de Datos', link: '/java/basico/tipos-datos', icon: '🔢' },
          { title: 'Control de Flujo', link: '/java/basico/control-flujo', icon: '🔀' },
          { title: 'Strings y Texto', link: '/java/basico/strings', icon: '📝' },
          { title: 'Arrays y Matrices', link: '/java/basico/arrays', icon: '📊' },
          { title: 'Scanner e Entrada', link: '/java/basico/scanner', icon: '⌨️' },
          { title: 'Excepciones', link: '/java/basico/excepciones', icon: '⚠️' },
          { title: 'Operadores', link: '/java/basico/operadores', icon: '➕' },
        ],
      },
      {
        id: 'poo',
        name: 'POO',
        fullName: 'Programación Orientada a Objetos',
        icon: '🏗️',
        description: 'Domina los pilares de la POO: clases, herencia, polimorfismo e interfaces.',
        lessons: [
          { title: 'Clases y Objetos', link: '/java/poo/clases-objetos', icon: '📦' },
          { title: 'Herencia', link: '/java/poo/herencia', icon: '🧬' },
          { title: 'Polimorfismo', link: '/java/poo/polimorfismo', icon: '🔄' },
          { title: 'Interfaces y Clases Abstractas', link: '/java/poo/interfaces-abstractas', icon: '🎭' },
        ],
      },
      {
        id: 'avanzado',
        name: 'Avanzado',
        fullName: 'Java Avanzado',
        icon: '⚡',
        description: 'Conceptos avanzados: colecciones, lambdas, streams, genéricos y la JVM.',
        lessons: [
          { title: 'Fundamentos de la Máquina de Java', link: '/java/avanzado/jvm', icon: '⚙️' },
          { title: 'Colecciones en Java', link: '/java/avanzado/colecciones', icon: '📦' },
          { title: 'Expresiones Lambda', link: '/java/avanzado/lambdas', icon: 'λ' },
          { title: 'Streams API', link: '/java/avanzado/streams', icon: '🌊' },
          { title: 'Genéricos', link: '/java/avanzado/genericos', icon: '<>' },
        ],
      },
      {
        id: 'bd',
        name: 'BD',
        fullName: 'Conexión a BD',
        icon: '🔗',
        description: 'JDBC, CRUD y persistencia: gestiona datos en bases de datos.',
        lessons: [
          { title: 'JDBC - Conectar a Bases de Datos', link: '/java/bd/jdbc', icon: '🔌' },
          { title: 'CRUD y Transacciones', link: '/java/bd/crud', icon: '💾' },
        ],
      },
    ],
    lessons: [
      { title: 'Tipos de Datos', link: '/java/basico/tipos-datos' },
      { title: 'Control de Flujo', link: '/java/basico/control-flujo' },
      { title: 'Strings y Texto', link: '/java/basico/strings' },
      { title: 'Arrays y Matrices', link: '/java/basico/arrays' },
      { title: 'Scanner e Entrada', link: '/java/basico/scanner' },
      { title: 'Excepciones', link: '/java/basico/excepciones' },
      { title: 'Operadores', link: '/java/basico/operadores' },
      { title: 'Clases y Objetos', link: '/java/poo/clases-objetos' },
      { title: 'Herencia', link: '/java/poo/herencia' },
      { title: 'Polimorfismo', link: '/java/poo/polimorfismo' },
      { title: 'Interfaces y Clases Abstractas', link: '/java/poo/interfaces-abstractas' },
      { title: 'Fundamentos de la Máquina de Java', link: '/java/avanzado/jvm' },
      { title: 'Colecciones en Java', link: '/java/avanzado/colecciones' },
      { title: 'Expresiones Lambda', link: '/java/avanzado/lambdas' },
      { title: 'Streams API', link: '/java/avanzado/streams' },
      { title: 'Genéricos', link: '/java/avanzado/genericos' },
      { title: 'JDBC - Conectar a Bases de Datos', link: '/java/bd/jdbc' },
      { title: 'CRUD y Transacciones', link: '/java/bd/crud' },
    ],
  },
  {
    id: 'sql',
    name: 'SQL - Bases de Datos',
    icon: '🗄️',
    description: 'DDL, DML, JOINs, consultas complejas',
    sections: [
      {
        id: 'basicos',
        name: 'SQL Básico',
        icon: '📖',
        description: 'Introducción, DDL, DML, consultas básicas',
        lessons: [
          { title: 'Introducción a SQL y Bases de Datos', link: '/sql/basicos/introduccion', icon: '📚' },
          { title: 'DDL - Data Definition Language', link: '/sql/basicos/ddl', icon: '⚙️' },
          { title: 'DML - Data Manipulation Language', link: '/sql/basicos/dml', icon: '✏️' },
        ],
      },
      {
        id: 'avanzado',
        name: 'SQL Avanzado',
        icon: '⚡',
        description: 'JOINs, GROUP BY, subconsultas, vistas',
        lessons: [
          { title: 'JOINs - Combinando Tablas', link: '/sql/avanzado/joins', icon: '🔗' },
          { title: 'Consultas Avanzadas', link: '/sql/avanzado/consultas-avanzadas', icon: '🔍' },
        ],
      },
      {
        id: 'gestion',
        name: 'Gestión de BBDD',
        icon: '👥',
        description: 'Administración: crear BD, usuarios, perfiles y permisos',
        lessons: [
          { title: 'Crear y Administrar Bases de Datos', link: '/sql/gestion/crear-bases-datos', icon: '➕' },
          { title: 'Usuarios y Permisos', link: '/sql/gestion/usuarios-permisos', icon: '🔐' },
          { title: 'Backup y Recuperación', link: '/sql/gestion/backup-recuperacion', icon: '💾' },
        ],
      },
      {
        id: 'lenguajes',
        name: 'Lenguajes de BBDD',
        icon: '🌐',
        description: 'SQL vs NoSQL: MySQL, PostgreSQL, MongoDB, etc.',
        lessons: [
          { title: 'SQL vs NoSQL - Comparativa', link: '/sql/lenguajes/sql-nosql', icon: '⚖️' },
          { title: 'MySQL - SQL Relacional', link: '/sql/lenguajes/mysql', icon: '🐬' },
          { title: 'PostgreSQL - SQL Avanzado', link: '/sql/lenguajes/postgresql', icon: '🐘' },
          { title: 'MongoDB - NoSQL Flexible', link: '/sql/lenguajes/mongodb', icon: '🍃' },
        ],
      },
    ],
    lessons: [
      { title: 'Introducción a SQL y Bases de Datos', link: '/sql/basicos/introduccion' },
      { title: 'DDL - Data Definition Language', link: '/sql/basicos/ddl' },
      { title: 'DML - Data Manipulation Language', link: '/sql/basicos/dml' },
      { title: 'JOINs - Combinando Tablas', link: '/sql/avanzado/joins' },
      { title: 'Consultas Avanzadas', link: '/sql/avanzado/consultas-avanzadas' },
      { title: 'Crear y Administrar Bases de Datos', link: '/sql/gestion/crear-bases-datos' },
      { title: 'Usuarios y Permisos', link: '/sql/gestion/usuarios-permisos' },
      { title: 'Backup y Recuperación', link: '/sql/gestion/backup-recuperacion' },
      { title: 'SQL vs NoSQL - Comparativa', link: '/sql/lenguajes/sql-nosql' },
      { title: 'MySQL - SQL Relacional', link: '/sql/lenguajes/mysql' },
      { title: 'PostgreSQL - SQL Avanzado', link: '/sql/lenguajes/postgresql' },
      { title: 'MongoDB - NoSQL Flexible', link: '/sql/lenguajes/mongodb' },
    ],
  },
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    icon: '🚀',
    description: 'Aplicaciones web profesionales con Spring Boot',
    landingPage: '/spring-boot/landing',
    sections: [
      {
        id: 'fundamentos',
        name: 'Spring Boot Fundamentos',
        icon: '📖',
        description: 'Introducción, setup, configuración inicial',
        lessons: [
          { title: 'Introducción a Spring Boot', link: '/spring-boot/fundamentos/introduccion', icon: '🚀' },
          { title: 'Setup y Configuración', link: '/spring-boot/fundamentos/configuracion', icon: '⚙️' },
          { title: 'Controladores y Rutas', link: '/spring-boot/fundamentos/controladores', icon: '🛣️' },
        ],
      },
      {
        id: 'avanzado',
        name: 'Spring Boot Avanzado',
        icon: '⚡',
        description: 'Servicios, JPA, validación, testing, seguridad',
        lessons: [
          { title: 'Servicios y Lógica de Negocio', link: '/spring-boot/avanzado/servicios', icon: '⚙️' },
          { title: 'Acceso a Datos con JPA', link: '/spring-boot/avanzado/jpa-hibernate', icon: '🗄️' },
          { title: 'Validación y Manejo de Errores', link: '/spring-boot/avanzado/validacion', icon: '✅' },
          { title: 'Testing', link: '/spring-boot/avanzado/testing', icon: '🧪' },
          { title: 'Seguridad con Spring Security', link: '/spring-boot/avanzado/spring-security', icon: '🔒' },
          { title: 'OAuth2 & JWT - Autenticación Profesional', link: '/spring-boot/avanzado/oauth2-jwt', icon: '🔐' },
        ],
      },
    ],
    lessons: [
      { title: 'Introducción a Spring Boot', link: '/spring-boot/fundamentos/introduccion' },
      { title: 'Setup y Configuración', link: '/spring-boot/fundamentos/configuracion' },
      { title: 'Controladores y Rutas', link: '/spring-boot/fundamentos/controladores' },
      { title: 'Servicios y Lógica de Negocio', link: '/spring-boot/avanzado/servicios' },
      { title: 'Acceso a Datos con JPA', link: '/spring-boot/avanzado/jpa-hibernate' },
      { title: 'Validación y Manejo de Errores', link: '/spring-boot/avanzado/validacion' },
      { title: 'Testing', link: '/spring-boot/avanzado/testing' },
      { title: 'Seguridad con Spring Security', link: '/spring-boot/avanzado/spring-security' },
      { title: 'OAuth2 & JWT - Autenticación Profesional', link: '/spring-boot/avanzado/oauth2-jwt' },
    ],
  },
  {
    id: 'entornos',
    name: 'Entornos de Desarrollo',
    icon: '🛠️',
    description: 'Herramientas, IDEs, arquitectura y mejores prácticas profesionales',
    sections: [
      {
        id: 'herramientas',
        name: 'Herramientas',
        icon: '🔧',
        description: 'IDEs, editores y herramientas esenciales de desarrollo',
        landingPage: '/entornos/herramientas',
        lessons: [
          { title: 'Concepto de Entorno de Desarrollo', link: '/entornos/herramientas/concepto', icon: '🎯' },
          { title: 'IDEs y Editores', link: '/entornos/herramientas/ides', icon: '💻' },
          { title: 'Codeium AI', link: '/entornos/herramientas/codeium', icon: '🤖' },
        ],
      },
      {
        id: 'arquitectura',
        name: 'Arquitectura y Patrones',
        icon: '🏗️',
        description: 'Arquitectura de software, patrones y mejores prácticas',
        landingPage: '/entornos/arquitectura',
        lessons: [
          { title: 'UML y Diagramas', link: '/entornos/arquitectura/uml', icon: '📐' },
          { title: 'Patrones de Diseño', link: '/entornos/arquitectura/patrones', icon: '🎯' },
          { title: 'Conceptos de Desarrollo', link: '/entornos/arquitectura/conceptos', icon: '📚' },
          { title: 'Testing y QA', link: '/entornos/arquitectura/testing', icon: '✅' },
          { title: 'Refactorización y SOLID', link: '/entornos/arquitectura/refactoring', icon: '🔄' },
        ],
      },
      {
        id: 'build-tools',
        name: 'Build & Herramientas',
        icon: '🔨',
        description: 'Maven, Gradle y construcción de proyectos profesionales',
        landingPage: '/entornos/build',
        lessons: [
          { title: 'Maven - Gestión de Proyectos', link: '/entornos/build/maven', icon: '📦' },
          { title: 'Gradle - Build Avanzado', link: '/entornos/build/gradle', icon: '⚙️' },
          { title: 'Gestión de Dependencias', link: '/entornos/build/dependencias', icon: '🔗' },
        ],
      },
      {
        id: 'devops',
        name: 'DevOps & Deployment',
        icon: '🚀',
        description: 'Docker, CI/CD, containerización y despliegue profesional',
        lessons: [
          { title: 'Docker - Containerización', link: '/entornos/devops/docker', icon: '🐳' },
          { title: 'Docker Compose - Multi-contenedor', link: '/entornos/devops/docker-compose', icon: '🔗' },
          { title: 'CI/CD - Automatización', link: '/entornos/devops/cicd', icon: '⚙️' },
          { title: 'GitHub Actions', link: '/entornos/devops/github-actions', icon: '🤖' },
          { title: 'Despliegue en Cloud', link: '/entornos/devops/cloud-deployment', icon: '☁️' },
        ],
      },
    ],
    lessons: [
      { title: 'Concepto de Entorno de Desarrollo', link: '/entornos/herramientas/concepto' },
      { title: 'IDEs y Editores', link: '/entornos/herramientas/ides' },
      { title: 'Codeium AI', link: '/entornos/herramientas/codeium' },
      { title: 'UML y Diagramas', link: '/entornos/arquitectura/uml' },
      { title: 'Patrones de Diseño', link: '/entornos/arquitectura/patrones' },
      { title: 'Conceptos de Desarrollo', link: '/entornos/arquitectura/conceptos' },
      { title: 'Testing y QA', link: '/entornos/arquitectura/testing' },
      { title: 'Refactorización y SOLID', link: '/entornos/arquitectura/refactoring' },
      { title: 'Maven - Gestión de Proyectos', link: '/entornos/build/maven' },
      { title: 'Gradle - Build Avanzado', link: '/entornos/build/gradle' },
      { title: 'Gestión de Dependencias', link: '/entornos/build/dependencias' },
      { title: 'Docker - Containerización', link: '/entornos/devops/docker' },
      { title: 'Docker Compose - Multi-contenedor', link: '/entornos/devops/docker-compose' },
      { title: 'CI/CD - Automatización', link: '/entornos/devops/cicd' },
      { title: 'GitHub Actions', link: '/entornos/devops/github-actions' },
      { title: 'Despliegue en Cloud (Vercel, Heroku, AWS, Azure)', link: '/entornos/devops/cloud-deployment' },
    ],
  },
  {
    id: 'proyecto',
    name: 'Proyecto Integrador',
    icon: '🚀',
    description: 'Proyecto final integrando Java Backend, Spring Boot, Bases de Datos y más',
    sections: [
      {
        id: 'planificacion',
        name: 'Planificación',
        icon: '📋',
        description: 'Definición de requisitos, arquitectura y diseño del proyecto',
        lessons: [
          { title: 'Definición del Proyecto', link: '/proyecto/planificacion/definicion', icon: '🎯' },
          { title: 'Requisitos y Especificaciones', link: '/proyecto/planificacion/requisitos', icon: '📋' },
          { title: 'Arquitectura y Diseño', link: '/proyecto/planificacion/arquitectura', icon: '🏗️' },
          { title: 'Ejemplos de Proyectos TFC', link: '/proyecto/planificacion/ejemplos', icon: '💡' },
        ],
      },
      {
        id: 'metodologia',
        name: 'Metodología',
        icon: '⚡',
        description: 'Agile, SCRUM y gestión del proyecto con Taiga',
        lessons: [
          { title: 'Agile y SCRUM', link: '/proyecto/metodologia/agile-scrum', icon: '⚡' },
          { title: 'Sprint 1', link: '/proyecto/metodologia/sprint-1', icon: '🚀' },
          { title: 'Sprint 2', link: '/proyecto/metodologia/sprint-2', icon: '🚀' },
        ],
      },
      {
        id: 'desarrollo',
        name: 'Desarrollo',
        icon: '💻',
        description: 'Implementación del backend con Java y Spring Boot',
        lessons: [
          { title: 'Setup del Proyecto', link: '/proyecto/desarrollo/setup', icon: '⚙️' },
          { title: 'Desarrollo Backend', link: '/proyecto/desarrollo/backend', icon: '🔧' },
          { title: 'Base de Datos', link: '/proyecto/desarrollo/database', icon: '🗄️' },
          { title: 'APIs REST', link: '/proyecto/desarrollo/apis', icon: '🌐' },
        ],
      },
      {
        id: 'testing',
        name: 'Testing',
        icon: '✅',
        description: 'Pruebas unitarias, integración y validación',
        lessons: [
          { title: 'Testing Unitario', link: '/proyecto/testing/unitario', icon: '🧪' },
          { title: 'Testing de Integración', link: '/proyecto/testing/integracion', icon: '🔗' },
          { title: 'Validación Final', link: '/proyecto/testing/validacion', icon: '✔️' },
        ],
      },
      {
        id: 'despliegue',
        name: 'Despliegue',
        icon: '📦',
        description: 'Empaquetado, documentación y despliegue a producción',
        lessons: [
          { title: 'Empaquetado y Build', link: '/proyecto/despliegue/build', icon: '📦' },
          { title: 'Documentación', link: '/proyecto/despliegue/documentacion', icon: '📖' },
          { title: 'Despliegue en Cloud', link: '/proyecto/despliegue/cloud', icon: '☁️' },
        ],
      },
      {
        id: 'retos',
        name: 'Retos DAW',
        icon: '🎯',
        description: 'Los 8 Retos del currículo con especificaciones y soluciones',
        lessons: [
          { title: 'REPTE 1: Especificación', link: '/proyecto/retos/1', icon: '📋' },
          { title: 'REPTE 2: Especificación Técnica', link: '/proyecto/retos/2', icon: '⚙️' },
          { title: 'REPTE 3: Elevator Pitch', link: '/proyecto/retos/3', icon: '🎤' },
          { title: 'REPTE 4: Organización Equipo', link: '/proyecto/retos/4', icon: '👥' },
          { title: 'REPTE 5: Agile & SCRUM', link: '/proyecto/retos/5', icon: '⚡' },
          { title: 'REPTE 6: Sprint 1', link: '/proyecto/retos/6', icon: '🚀' },
          { title: 'REPTE 7: Sprint 2', link: '/proyecto/retos/7', icon: '🚀' },
          { title: 'REPTE 8: Sprint Final', link: '/proyecto/retos/8', icon: '🎯' },
        ],
      },
      {
        id: 'ejemplos',
        name: 'Ejemplos de TFC',
        icon: '💡',
        description: '12+ proyectos desarrollados y viables para tu Trabajo de Fin de Curso',
        lessons: [
          { title: 'LibroHub - Marketplace de Libros Usados', link: '/proyecto/ejemplos/1', icon: '📚' },
          { title: 'SportGear - E-commerce de Equipamiento', link: '/proyecto/ejemplos/2', icon: '🏃' },
          { title: 'ClinicaPro - Gestión de Clínica Médica', link: '/proyecto/ejemplos/3', icon: '🏥' },
          { title: 'PropertyHub - Plataforma de Alquiler', link: '/proyecto/ejemplos/4', icon: '🏘️' },
          { title: 'GamerHub - Red Social de Gamers', link: '/proyecto/ejemplos/5', icon: '🎮' },
          { title: 'TravelDiaries - Red de Viajeros', link: '/proyecto/ejemplos/6', icon: '✈️' },
          { title: 'CodeLearning - Plataforma de Cursos', link: '/proyecto/ejemplos/7', icon: '💻' },
          { title: 'JobMatch - Portal de Empleo', link: '/proyecto/ejemplos/8', icon: '💼' },
          { title: 'ExpenseSplitter - Gestor de Gastos', link: '/proyecto/ejemplos/9', icon: '💰' },
          { title: 'TaskFlow - Gestor de Proyectos', link: '/proyecto/ejemplos/10', icon: '📊' },
          { title: 'RecipeShare - Red de Recetas', link: '/proyecto/ejemplos/11', icon: '🍳' },
          { title: 'PetCare - Red Social de Mascotas', link: '/proyecto/ejemplos/12', icon: '🐕' },
        ],
      },
    ],
    lessons: [
      { title: 'Definición del Proyecto', link: '/proyecto/planificacion/definicion' },
      { title: 'Requisitos y Especificaciones', link: '/proyecto/planificacion/requisitos' },
      { title: 'Arquitectura y Diseño', link: '/proyecto/planificacion/arquitectura' },
      { title: 'Ejemplos de Proyectos TFC', link: '/proyecto/planificacion/ejemplos' },
      { title: 'Agile y SCRUM', link: '/proyecto/metodologia/agile-scrum' },
      { title: 'Sprint 1', link: '/proyecto/metodologia/sprint-1' },
      { title: 'Sprint 2', link: '/proyecto/metodologia/sprint-2' },
      { title: 'Setup del Proyecto', link: '/proyecto/desarrollo/setup' },
      { title: 'Desarrollo Backend', link: '/proyecto/desarrollo/backend' },
      { title: 'Base de Datos', link: '/proyecto/desarrollo/database' },
      { title: 'APIs REST', link: '/proyecto/desarrollo/apis' },
      { title: 'Testing Unitario', link: '/proyecto/testing/unitario' },
      { title: 'Testing de Integración', link: '/proyecto/testing/integracion' },
      { title: 'Validación Final', link: '/proyecto/testing/validacion' },
      { title: 'Empaquetado y Build', link: '/proyecto/despliegue/build' },
      { title: 'Documentación', link: '/proyecto/despliegue/documentacion' },
      { title: 'Despliegue en Cloud', link: '/proyecto/despliegue/cloud' },
      { title: 'REPTE 1: Especificación del Proyecto', link: '/proyecto/retos/1' },
      { title: 'REPTE 2: Especificación de Requisitos', link: '/proyecto/retos/2' },
      { title: 'REPTE 3: Diseño de Arquitectura y BD', link: '/proyecto/retos/3' },
      { title: 'REPTE 4: Prototipo y Diseño Visual', link: '/proyecto/retos/4' },
      { title: 'REPTE 5: Configuración Agile/SCRUM', link: '/proyecto/retos/5' },
      { title: 'REPTE 6: Primer Sprint Development', link: '/proyecto/retos/6' },
      { title: 'REPTE 7: Second Sprint Development', link: '/proyecto/retos/7' },
      { title: 'REPTE 8: Final Sprint & Deployment', link: '/proyecto/retos/8' },
      { title: 'LibroHub - Marketplace de Libros Usados', link: '/proyecto/ejemplos/1' },
      { title: 'SportGear - E-commerce de Equipamiento', link: '/proyecto/ejemplos/2' },
      { title: 'ClinicaPro - Gestión de Clínica Médica', link: '/proyecto/ejemplos/3' },
      { title: 'PropertyHub - Plataforma de Alquiler', link: '/proyecto/ejemplos/4' },
      { title: 'GamerHub - Red Social de Gamers', link: '/proyecto/ejemplos/5' },
      { title: 'TravelDiaries - Red de Viajeros', link: '/proyecto/ejemplos/6' },
      { title: 'CodeLearning - Plataforma de Cursos', link: '/proyecto/ejemplos/7' },
      { title: 'JobMatch - Portal de Empleo', link: '/proyecto/ejemplos/8' },
      { title: 'ExpenseSplitter - Gestor de Gastos', link: '/proyecto/ejemplos/9' },
      { title: 'TaskFlow - Gestor de Proyectos', link: '/proyecto/ejemplos/10' },
      { title: 'RecipeShare - Red de Recetas', link: '/proyecto/ejemplos/11' },
      { title: 'PetCare - Red Social de Mascotas', link: '/proyecto/ejemplos/12' },
    ],
  },
  {
    id: 'metodologias',
    name: 'Metodologías & Procesos',
    icon: '📊',
    description: 'Prácticas, metodologías y procesos para desarrollo profesional',
    sections: [
      {
        id: 'agile-scrum',
        name: 'Agile/SCRUM',
        fullName: 'Metodología Agile y SCRUM',
        icon: '⚡',
        description: 'Metodología ágil para gestión de proyectos iterativos',
        lessons: [
          { title: 'Introducción a Agile', link: '/metodologias/agile-scrum/introduccion', icon: '📖' },
          { title: 'SCRUM Framework', link: '/metodologias/agile-scrum/scrum', icon: '🎯' },
          { title: 'Sprints y Planning', link: '/metodologias/agile-scrum/sprints', icon: '📅' },
        ],
      },
      {
        id: 'clean-code',
        name: 'Clean Code',
        fullName: 'Código Limpio y Mantenible',
        icon: '✨',
        description: 'Principios y prácticas para escribir código de calidad',
        lessons: [
          { title: 'Nombres Significativos', link: '/metodologias/clean-code/nombres', icon: '📝' },
          { title: 'Funciones Limpias', link: '/metodologias/clean-code/funciones', icon: '⚙️' },
          { title: 'Estructura y Formato', link: '/metodologias/clean-code/estructura', icon: '🏗️' },
          { title: 'SOLID y Refactorización', link: '/metodologias/clean-code/solid', icon: '🎯' },
          { title: 'Patrones de Diseño', link: '/metodologias/clean-code/patrones', icon: '🎨' },
          { title: 'Antipatrones: Qué NO Hacer', link: '/metodologias/clean-code/antipatrones', icon: '⛔' },
        ],
      },
      {
        id: 'testing',
        name: 'Testing',
        fullName: 'Pruebas de Software',
        icon: '🧪',
        description: 'Estrategias y tipos de testing para garantizar calidad',
        lessons: [
          { title: 'Testing Unitario', link: '/metodologias/testing/unitario', icon: '🔍' },
          { title: 'Testing de Integración', link: '/metodologias/testing/integracion', icon: '🔗' },
          { title: 'Testing de Aceptación', link: '/metodologias/testing/aceptacion', icon: '✅' },
        ],
      },
      {
        id: 'devops',
        name: 'DevOps',
        fullName: 'DevOps y CI/CD',
        icon: '🚀',
        description: 'Prácticas para automatización, integración y despliegue continuo',
        lessons: [
          { title: 'Introducción a DevOps', link: '/metodologias/devops/introduccion', icon: '📖' },
          { title: 'CI/CD Pipelines', link: '/metodologias/devops/cicd', icon: '⚙️' },
          { title: 'Monitoreo y Logs', link: '/metodologias/devops/monitoreo', icon: '📊' },
        ],
      },
    ],
    lessons: [
      { title: 'Introducción a Agile', link: '/metodologias/agile-scrum/introduccion' },
      { title: 'SCRUM Framework', link: '/metodologias/agile-scrum/scrum' },
      { title: 'Sprints y Planning', link: '/metodologias/agile-scrum/sprints' },
      { title: 'Nombres Significativos', link: '/metodologias/clean-code/nombres' },
      { title: 'Funciones Limpias', link: '/metodologias/clean-code/funciones' },
      { title: 'Estructura y Formato', link: '/metodologias/clean-code/estructura' },
      { title: 'SOLID y Refactorización', link: '/metodologias/clean-code/solid' },
      { title: 'Patrones de Diseño', link: '/metodologias/clean-code/patrones' },
      { title: 'Antipatrones: Qué NO Hacer', link: '/metodologias/clean-code/antipatrones' },
      { title: 'Testing Unitario', link: '/metodologias/testing/unitario' },
      { title: 'Testing de Integración', link: '/metodologias/testing/integracion' },
      { title: 'Testing de Aceptación', link: '/metodologias/testing/aceptacion' },
      { title: 'Introducción a DevOps', link: '/metodologias/devops/introduccion' },
      { title: 'CI/CD Pipelines', link: '/metodologias/devops/cicd' },
      { title: 'Monitoreo y Logs', link: '/metodologias/devops/monitoreo' },
    ],
  }
];
